// ============================================================
// RHCSA MASTER — All Data
// Author: Mohamed TAIEB | mohamed.taieb.gl@gmail.com
// ============================================================

// ── DEFINITIONS ─────────────────────────────────────────────
const DEFS = [
  {term:'SELinux',def:'Security-Enhanced Linux. Mandatory access control (MAC) built into the kernel. Restricts what processes and users can do, even as root. Modes: Enforcing, Permissive, Disabled.'},
  {term:'LVM',def:'Logical Volume Manager. Abstracts physical disks into flexible logical volumes. Supports resizing, snapshots, and adding disks without rebooting.'},
  {term:'Physical Volume (PV)',def:'A disk/partition initialized for LVM with pvcreate. The raw building block of LVM storage.'},
  {term:'Volume Group (VG)',def:'Pool of storage from one or more PVs (vgcreate). Acts like one big virtual disk. PVs can be added later with vgextend.'},
  {term:'Logical Volume (LV)',def:'Virtual partition carved from a VG (lvcreate). This is what you format and mount. Can be extended online.'},
  {term:'XFS',def:'Default RHEL 9 filesystem. High-performance journaling. Can grow ONLINE with xfs_growfs. CANNOT shrink — ever.'},
  {term:'ext4',def:'Extended Filesystem 4. Can grow and shrink (resize2fs). Must be unmounted to shrink. Good for cases where shrinking is needed.'},
  {term:'/etc/fstab',def:'File Systems Table. Defines persistent mounts loaded at boot. Format: device mountpoint fstype options dump pass.'},
  {term:'autofs',def:'Auto-mounter service. Mounts filesystems on-demand when accessed, unmounts after idle timeout. Perfect for NFS home dirs.'},
  {term:'NFS',def:'Network File System. Mount remote directories locally. Client: mount -t nfs server:/path /mnt. Use _netdev in fstab.'},
  {term:'systemd',def:'System and service manager for RHEL 9. Manages services (units), boot targets, journal, sockets, timers.'},
  {term:'systemctl',def:'Control systemd: start/stop/enable/disable/status/mask/list-units. enable --now = enable+start in one step.'},
  {term:'journalctl',def:'Query systemd journal. Filter by unit (-u), priority (-p), time (--since), boot (-b). Replaces /var/log/*.'},
  {term:'Unit File',def:'systemd config file (.service .socket .target .timer .mount). In /etc/systemd/system/ for admin-created units.'},
  {term:'Target',def:'systemd unit grouping other units. Replaces runlevels: multi-user.target=3, graphical.target=5, rescue.target=1.'},
  {term:'GRUB2',def:'GRand Unified Bootloader v2. Config: /etc/default/grub (edit this). Regenerate: grub2-mkconfig -o /boot/grub2/grub.cfg.'},
  {term:'SELinux Context',def:'Label on every file/process: user:role:TYPE:level. The TYPE field controls access. Example: httpd_sys_content_t.'},
  {term:'SELinux Boolean',def:'On/off switch for policy rules. Permanent: setsebool -P name on. List: getsebool -a. Describe: semanage boolean -l.'},
  {term:'restorecon',def:'Apply SELinux contexts from policy to files. Run after semanage fcontext to activate the new rules. -Rv for recursive.'},
  {term:'semanage',def:'Manage SELinux policy permanently: file contexts, ports, booleans, users. Unlike chcon, survives relabels.'},
  {term:'chcon',def:'TEMPORARY SELinux context change. Reverts on relabeling. Use only for testing. Always follow up with semanage+restorecon.'},
  {term:'firewalld',def:'Dynamic firewall using zones. CLI: firewall-cmd. Always use --permanent + --reload for persistence.'},
  {term:'Zone (firewalld)',def:'Named trust level: public (default), trusted, home, work, dmz, drop, block. Interfaces/sources are assigned to zones.'},
  {term:'ACL',def:'Access Control List. Per-user/group permissions beyond standard owner/group/other. setfacl to set, getfacl to view.'},
  {term:'SUID',def:'Set User ID (4000). Executable runs as its OWNER regardless of who launches it. Example: /usr/bin/passwd runs as root.'},
  {term:'SGID',def:'Set Group ID (2000). On files: runs as file group. On directories: new files inherit directory group.'},
  {term:'Sticky Bit',def:'On directories (1000): users can ONLY delete their own files, not others. Classic example: /tmp (drwxrwxrwt).'},
  {term:'umask',def:'Subtracted from default permissions. Files: 666-umask. Dirs: 777-umask. Default 0022 → files=644, dirs=755.'},
  {term:'cron',def:'Recurring job scheduler. crontab -e for user jobs. Format: min hour dom month dow command. Use full paths.'},
  {term:'at',def:'One-time future job. at 14:30 / at now+2h. List: atq. Remove: atrm N. Install: dnf install at.'},
  {term:'nice / renice',def:'CPU priority. Range -20 (highest) to 19 (lowest). Default 0. Only root can set negative. renice changes running processes.'},
  {term:'dnf',def:'Package manager for RHEL 9. Install/remove/update packages. whatprovides finds which package provides a file/command.'},
  {term:'RPM',def:'Red Hat Package format. rpm -q (query) -ql (list files) -qf (which pkg owns file) -V (verify) -ivh (install).'},
  {term:'AppStream',def:'RHEL repo with multiple software versions as modules/streams/profiles. Enable: dnf module enable name:stream.'},
  {term:'NetworkManager',def:'Network management service in RHEL 9. Primary CLI: nmcli. Stores connections in /etc/NetworkManager/system-connections/.'},
  {term:'nmcli',def:'NetworkManager CLI. Modify connections: nmcli con mod NAME setting value. Apply: nmcli con up NAME.'},
  {term:'ss',def:'Socket Statistics. Replaces netstat. ss -tlnp = TCP Listening Numeric with Process names.'},
  {term:'Podman',def:'Daemonless container engine for RHEL 9. Docker-compatible syntax. Runs rootless by default. No daemon required.'},
  {term:'Rootless container',def:'Container running as non-root user. More secure. Managed with systemctl --user. Needs loginctl enable-linger for persistence.'},
  {term:'/etc/sudoers',def:'sudo privileges config. ALWAYS edit with visudo. Format: user HOST=(runas) NOPASSWD: /path/to/cmd.'},
  {term:'chage',def:'Password aging: chage -l (list) -M (max days) -m (min) -W (warn) -E (expiry date) -d 0 (force change now).'},
  {term:'rd.break',def:'Kernel boot param. Breaks boot before root is mounted. Used for root password reset. Add to GRUB linux line.'},
  {term:'/.autorelabel',def:'Creating this file triggers full SELinux filesystem relabeling on next boot. REQUIRED after root password reset.'},
  {term:'loginctl enable-linger',def:'Allows user systemd services to survive logout and start at boot. Required for rootless container persistence.'},
  {term:'audit2why',def:'Explains SELinux denials in human language. Input: ausearch -m avc output. Sibling: audit2allow generates policy.'},
];

// ── 2-WEEK PLAN ──────────────────────────────────────────────
const PLAN = [
  {day:1,week:1,title:'Linux Foundations',topics:'Shell navigation, man pages, FHS, pwd, ls, cd, mkdir, touch, cp, mv, rm, file, stat',focus:'essentials',hours:3},
  {day:2,week:1,title:'Files & Text Processing',topics:'vim, cat, grep, find, I/O redirection, pipes, tar, gzip, ssh, scp, rsync',focus:'essentials',hours:4},
  {day:3,week:1,title:'Users & Groups',topics:'useradd, usermod, groupadd, passwd, chage, su, sudo, visudo, /etc/passwd, /etc/shadow, /etc/group',focus:'users',hours:3},
  {day:4,week:1,title:'Permissions & ACL',topics:'chmod, chown, umask, SUID/SGID/Sticky, setfacl, getfacl, default ACLs, mask',focus:'permissions',hours:4},
  {day:5,week:1,title:'Storage & Filesystems',topics:'fdisk, parted, mkfs.xfs/ext4, blkid, mount, /etc/fstab, swap file/partition',focus:'storage',hours:4},
  {day:6,week:1,title:'LVM Deep Dive',topics:'pvcreate, vgcreate, lvcreate, lvextend, xfs_growfs, resize2fs, vgextend, pvs/vgs/lvs, autofs, NFS',focus:'storage',hours:4},
  {day:7,week:1,title:'Week 1 Lab Day 🔬',topics:'HANDS-ON: Set up full user env, shared dirs with SGID+sticky, complete LVM workflow, fstab entries. Fix everything broken.',focus:'labs',hours:5},
  {day:8,week:2,title:'Processes & Scheduling',topics:'ps, top, kill, nice, renice, bg/fg/jobs, nohup, crontab, at, systemd timers',focus:'processes',hours:3},
  {day:9,week:2,title:'Networking',topics:'nmcli (static IP, DNS, gateway, routes), ip, ss, hostnamectl, /etc/hosts, dig, ping',focus:'networking',hours:3},
  {day:10,week:2,title:'Services & Software',topics:'systemctl enable/start/status/mask, journalctl, custom units, timers, dnf, rpm, modules, repos',focus:'services',hours:4},
  {day:11,week:2,title:'SELinux Mastery',topics:'getenforce, semanage fcontext, restorecon, setsebool -P, semanage port, ausearch, audit2why',focus:'security',hours:4},
  {day:12,week:2,title:'Firewall + Containers + Scripting',topics:'firewall-cmd zones/services/ports/rich-rules, podman rootless, generate systemd, bash scripts',focus:'security',hours:4},
  {day:13,week:2,title:'Boot, Recovery & Wrap-up',topics:'GRUB2 config, rd.break root reset, rescue/emergency mode, systemd targets, NFS/autofs review',focus:'boot',hours:4},
  {day:14,week:2,title:'Full Mock Exam Day ⏱️',topics:'3h timed mock exam → review every wrong answer → redo failed labs → scan cheat sheet',focus:'exam',hours:6},
];

// ── QUIZ QUESTIONS (50 total) ────────────────────────────────
const QUIZ_Q = [
  // ESSENTIALS (8)
  {d:'essentials',q:'Which command finds all regular files with SUID bit set?',o:['find / -type f -perm 4000','find / -type f -perm /4000','find / -suid -type f','ls -laR / | grep s'],a:1,e:'/4000 matches files WHERE the SUID bit (4000) is set among other bits. -4000 means EXACTLY 4000. /4000 = any file with that bit.'},
  {d:'essentials',q:'Redirect both stdout and stderr of "cmd" to /tmp/out.txt:',o:['cmd > /tmp/out.txt 2> /tmp/out.txt','cmd &> /tmp/out.txt','cmd | /tmp/out.txt 2>&1','cmd > /tmp/out.txt && 2> /tmp/out.txt'],a:1,e:'&> file redirects both stdout(1) and stderr(2) to the same file. Also valid: cmd > file 2>&1 (2>&1 must come after >).'},
  {d:'essentials',q:'"tar -czvf backup.tar.gz /etc" — what does z do?',o:['Creates the archive','Compresses with gzip','Runs verbosely','Names the output file'],a:1,e:'z = gzip compression. c=create, z=gzip, v=verbose, f=specify filename. Result: a gzip-compressed tar archive (.tar.gz).'},
  {d:'essentials',q:'In vim, how do you replace ALL occurrences of "foo" with "bar"?',o:[':s/foo/bar/',':%s/foo/bar/g',':replace foo bar all',':%replace/foo/bar'],a:1,e:':%s/foo/bar/g — % applies substitution to ALL lines, g flag replaces ALL occurrences per line. Without g, only first match per line.'},
  {d:'essentials',q:'Which command displays the first 15 lines of a file?',o:['head -15 file','head -n 15 file','top 15 file','head file 15'],a:1,e:'head -n 15 file shows first 15 lines. -n specifies line count. Both "head -15 file" and "head -n 15 file" work.'},
  {d:'essentials',q:'"find /etc -name \'*.conf\' -mtime -7" finds files:',o:['Modified more than 7 days ago','Modified exactly 7 days ago','Modified in the last 7 days','Larger than 7KB with .conf extension'],a:2,e:'-mtime -7 = modified less than 7 days ago (within last 7 days). +7 = more than 7 days ago. =7 = exactly 7 days ago.'},
  {d:'essentials',q:'Which command appends output to a file WITHOUT overwriting?',o:['cmd > file','cmd >> file','cmd &> file','cmd | file'],a:1,e:'>> appends to file. > overwrites. &>> appends both stdout and stderr. Always use >> when you want to keep existing content.'},
  {d:'essentials',q:'What does "grep -v pattern file" do?',o:['Shows only matching lines','Shows lines NOT matching pattern','Counts matches','Shows line numbers of matches'],a:1,e:'-v inverts the match — shows lines that do NOT contain the pattern. Useful for: grep -v "^#" file (remove comment lines).'},
  // USERS (7)
  {d:'users',q:'Which flag adds alice to devs WITHOUT removing her current groups?',o:['usermod -G devs alice','usermod -aG devs alice','usermod -g devs alice','groupmod -a alice devs'],a:1,e:'CRITICAL TRAP: -G alone REPLACES all supplementary groups! Always -aG (append+groups). -g changes the PRIMARY group only.'},
  {d:'users',q:'Force alice to change password at next login:',o:['passwd -e alice','chage -d 0 alice','usermod --expire alice','passwd --reset alice'],a:1,e:'chage -d 0 sets last change date to epoch 0, forcing immediate password change. passwd -e alice also works and is equivalent.'},
  {d:'users',q:'Which file stores hashed passwords on RHEL 9?',o:['/etc/passwd','/etc/shadow','/etc/security/passwd','/etc/login.defs'],a:1,e:'/etc/shadow stores hashed passwords. Readable only by root. /etc/passwd has "x" in the password field pointing to shadow.'},
  {d:'users',q:'Create a system account "svc" with no home, no login shell:',o:['useradd -s /sbin/nologin svc','useradd -r -s /sbin/nologin svc','adduser --system svc','useradd --noskel svc'],a:1,e:'-r creates system account (UID < 1000, no home dir by default). -s /sbin/nologin prevents interactive login.'},
  {d:'users',q:'What format allows bob to restart httpd with no password in sudoers?',o:['bob ALL=httpd','bob ALL=(root) NOPASSWD: /usr/bin/systemctl restart httpd','bob=root NOPASSWD httpd','%bob ALL httpd restart'],a:1,e:'Full format: user HOST=(run-as) NOPASSWD: /full/path/to/command. Full path required. Edited safely with visudo only.'},
  {d:'users',q:'chage -M 90 alice sets:',o:['Minimum password age to 90 days','Maximum password age to 90 days','Account expiry in 90 days','Warning period to 90 days'],a:1,e:'-M sets MAXIMUM password age. After 90 days, alice must change it. -m=minimum, -W=warning, -E=expiry date, -I=inactive.'},
  {d:'users',q:'su - alice vs su alice — what is the difference?',o:['No difference','su - loads alice\'s full login environment; su alice keeps current env','su - is for root only','su alice is more secure'],a:1,e:'su - (with dash) = login shell: loads alice\'s PATH, HOME, env vars. su alice = non-login shell: keeps caller\'s environment.'},
  // PERMISSIONS (6)
  {d:'permissions',q:'chmod 2770 /dir sets which special bit?',o:['SUID','SGID','Sticky','Execute for all'],a:1,e:'2000=SGID. On a directory, SGID makes new files inherit the directory\'s group, not the creator\'s primary group. 3770=SGID+Sticky.'},
  {d:'permissions',q:'"setfacl -d -m u:bob:rw- /dir" does what?',o:['Gives bob rw on /dir now','Sets bob\'s DEFAULT ACL so NEW files in /dir get rw','Deletes bob\'s ACL from /dir','Overwrites all ACLs with bob\'s'],a:1,e:'-d = default ACL. New files created inside /dir automatically inherit this ACL entry. Without -d, only existing files are affected.'},
  {d:'permissions',q:'A file shows "-rwsr-xr-x". The "s" in user position means:',o:['File is immutable','SUID set: runs as file owner','SGID set: runs as file group','Sticky bit'],a:1,e:'s where x was in owner position = SUID. File runs with owner\'s privileges. Example: /usr/bin/passwd (owner=root → runs as root).'},
  {d:'permissions',q:'getfacl shows a "+" at end of ls -l permissions. What does it indicate?',o:['File has extended attributes','ACL is active on this file','File is immutable','SUID is set'],a:1,e:'A "+" at the end of permissions in ls -l output means the file/dir has an ACL. Use getfacl to see the full ACL.'},
  {d:'permissions',q:'umask 027: permissions of a new regular file?',o:['750','640','027','777'],a:1,e:'Files default 666 - 027 = 640 (rw-r-----). Dirs default 777 - 027 = 750 (rwxr-x---). umask bits are subtracted.'},
  {d:'permissions',q:'Which sticky bit permission string on /tmp is correct?',o:['drwxrwxrwx','drwxrwxrwt','drwxrwsrwx','drwxrwxr-T'],a:1,e:'drwxrwxrwt — the "t" at the end (other execute position) shows sticky bit is set. Capital "T" = sticky set but other lacks execute.'},
  // STORAGE (7)
  {d:'storage',q:'Correct LVM creation order:',o:['lvcreate→vgcreate→pvcreate','pvcreate→vgcreate→lvcreate','vgcreate→pvcreate→lvcreate','mkfs→lvcreate→pvcreate'],a:1,e:'PV (pvcreate) → VG (vgcreate) → LV (lvcreate) → mkfs → mount. Physical → Group → Logical → Format → Use.'},
  {d:'storage',q:'After lvextend on an XFS logical volume, how do you grow the filesystem?',o:['resize2fs /dev/vg/lv','xfs_growfs /mountpoint','xfs_repair /mountpoint','fsck.xfs /dev/vg/lv'],a:1,e:'xfs_growfs /MOUNTPOINT grows XFS to fill the LV. Can be done ONLINE (while mounted)! resize2fs is for ext4 only.'},
  {d:'storage',q:'Which fstab option is required for NFS to avoid boot failure?',o:['noauto','_netdev','nofail','lazy'],a:1,e:'_netdev = "this mount needs the network". Without it, boot tries to mount NFS before network is ready, causing emergency mode.'},
  {d:'storage',q:'Swap file must have which permissions?',o:['777','644','600','400'],a:2,e:'Swap files must be mode 600 (rw-------). mkswap will refuse or warn with wrong permissions. Always: chmod 600 /swapfile.'},
  {d:'storage',q:'blkid /dev/sdb1 shows UUID. Why use UUID in fstab instead of /dev/sdb1?',o:['It\'s shorter','Device names can change; UUIDs are stable identifiers','Required by RHEL 9','Performance improvement'],a:1,e:'Device names (/dev/sdb1) can change if disks are added/removed. UUIDs never change. Always use UUID in fstab for stability.'},
  {d:'storage',q:'XFS filesystem limitation compared to ext4:',o:['XFS cannot be mounted','XFS cannot grow','XFS cannot shrink','XFS requires more RAM'],a:2,e:'XFS cannot shrink — at all. Only extend with xfs_growfs. ext4 can both grow (resize2fs) and shrink (must unmount first).'},
  {d:'storage',q:'"vgextend myvg /dev/sdc1" — what must be done FIRST?',o:['lvcreate','mkfs on /dev/sdc1','pvcreate /dev/sdc1','fdisk /dev/sdc1'],a:2,e:'pvcreate /dev/sdc1 must be done first to initialize it as a PV. Then vgextend adds it to the VG. Then lvextend can use the space.'},
  // PROCESSES (5)
  {d:'processes',q:'Which signal gracefully terminates a process (default for kill)?',o:['SIGKILL (9)','SIGHUP (1)','SIGTERM (15)','SIGSTOP (19)'],a:2,e:'SIGTERM (15) is the default. Process can catch it and clean up. SIGKILL (9) cannot be caught — immediate forced termination.'},
  {d:'processes',q:'Cron expression to run daily at 2:30 AM:',o:['2 30 * * *','30 2 * * *','* 2 30 * *','30 2 0 0 0'],a:1,e:'Format: MINUTE HOUR DOM MONTH DOW. So 30=minute, 2=2AM, * * * = every day, every month, every weekday.'},
  {d:'processes',q:'Run a command that survives after you log out:',o:['bg command','nohup command &','nice command','setsid command'],a:1,e:'nohup cmd & — nohup ignores SIGHUP (sent when shell exits). & runs in background. Without nohup, background jobs die on logout.'},
  {d:'processes',q:'"nice -n 15 cmd" — what priority does cmd run with?',o:['Highest (fastest)','Low priority (niceness 15)','Root priority','Default priority'],a:1,e:'nice -20 = highest priority, nice 19 = lowest. 15 = low priority, below normal. Only root can use negative values.'},
  {d:'processes',q:'What does "jobs" command show?',o:['All system processes','Background/stopped jobs in current shell','Scheduled cron jobs','Systemd service status'],a:1,e:'jobs lists background and suspended jobs in the CURRENT shell session. Use fg %N to bring job N to foreground.'},
  // NETWORKING (5)
  {d:'networking',q:'Set static IP 10.0.0.5/24 on connection "eth0":',o:['nmcli con mod eth0 ip 10.0.0.5/24','nmcli connection modify eth0 ipv4.addresses 10.0.0.5/24','ifconfig eth0 10.0.0.5/24','ip addr set eth0 10.0.0.5/24'],a:1,e:'nmcli con mod "NAME" ipv4.addresses "IP/mask". Also need: ipv4.method manual, ipv4.gateway, ipv4.dns, then nmcli con up NAME.'},
  {d:'networking',q:'Show listening TCP ports with process names:',o:['netstat -tlnp','ss -tlnp','nmap -sT localhost','ip link show'],a:1,e:'ss -tlnp: t=TCP, l=Listening, n=Numeric (no DNS), p=Process names. ss replaces deprecated netstat on modern systems.'},
  {d:'networking',q:'Set hostname permanently on RHEL 9:',o:['hostname server1','echo server1 > /etc/hostname','hostnamectl set-hostname server1','nmcli general hostname server1'],a:2,e:'hostnamectl set-hostname NAME is the modern standard. Updates /etc/hostname and applies immediately. Survives reboot.'},
  {d:'networking',q:'Which file maps hostnames to IPs without querying DNS?',o:['/etc/resolv.conf','/etc/nsswitch.conf','/etc/hosts','/etc/hostname'],a:2,e:'/etc/hosts is checked before DNS (per /etc/nsswitch.conf "hosts: files dns"). Add: "192.168.1.10 server1.lab server1".'},
  {d:'networking',q:'After nmcli con modify, when do settings take effect?',o:['Immediately','After reboot','After running: nmcli con up NAME','After systemctl restart NetworkManager'],a:2,e:'nmcli con modify only changes the stored config. You must run "nmcli con up NAME" (or down+up) to apply the new settings.'},
  // SERVICES (4)
  {d:'services',q:'Enable httpd AND start it right now in one command:',o:['systemctl enable httpd','systemctl start httpd','systemctl enable --now httpd','service httpd start enable'],a:2,e:'systemctl enable --now = enable (boot) + start (now). Two actions in one command. Very common in exam tasks.'},
  {d:'services',q:'View error-level+ logs for sshd from current boot:',o:['journalctl -u sshd -p err -b','journalctl --unit=sshd --error','journalctl sshd error boot','grep error /var/log/sshd'],a:0,e:'-u sshd: filter by unit. -p err: priority error and above (crit,alert,emerg). -b: current boot only. Stack flags freely.'},
  {d:'services',q:'After creating a unit file in /etc/systemd/system/, what is required?',o:['systemctl restart','systemctl reload','systemctl daemon-reload','systemctl refresh'],a:2,e:'daemon-reload makes systemd re-read ALL unit files. Without it, your new/changed unit file is completely ignored.'},
  {d:'services',q:'"systemctl mask httpd" — effect?',o:['Temporarily stops httpd','Prevents httpd from starting by ANY means','Disables at boot only','Hides httpd status'],a:1,e:'mask creates /etc/systemd/system/httpd.service → /dev/null symlink. Nothing can start it. Stronger than disable. Undo: unmask.'},
  // SOFTWARE (4)
  {d:'software',q:'Find which package provides /usr/bin/semanage:',o:['rpm -q semanage','dnf whatprovides /usr/bin/semanage','dnf search semanage','rpm -qi semanage'],a:1,e:'dnf whatprovides (or dnf provides) finds which package provides a file path or binary. Essential when exam says "install the package that provides X".'},
  {d:'software',q:'List files installed by the httpd package:',o:['dnf files httpd','rpm -ql httpd','dnf list httpd','rpm -qi httpd'],a:1,e:'rpm -ql httpd: q=query, l=list files. Shows every file installed by the package. -qi shows package info/description.'},
  {d:'software',q:'Enable PHP 8.1 module stream:',o:['dnf install php:8.1','dnf module enable php:8.1','dnf stream enable php 8.1','dnf module set php=8.1'],a:1,e:'dnf module enable php:8.1 enables the stream. Then install: dnf install php or dnf module install php:8.1/profile.'},
  {d:'software',q:'Find which installed package owns /etc/httpd/conf/httpd.conf:',o:['dnf owns /etc/httpd/conf/httpd.conf','rpm -qf /etc/httpd/conf/httpd.conf','rpm -ql httpd | grep httpd.conf','dnf provides httpd.conf'],a:1,e:'rpm -qf /path/to/file finds the package that installed that file. Works for any file path on the system.'},
  // SECURITY (5)
  {d:'security',q:'Permanently fix SELinux context for /webdata (served by httpd):',o:['chcon -Rt httpd_sys_content_t /webdata','semanage fcontext -a -t httpd_sys_content_t "/webdata(/.*)?" && restorecon -Rv /webdata','setenforce 0','setsebool -P httpd 1'],a:1,e:'semanage fcontext = permanent policy rule. restorecon = apply it. chcon = temporary (lost on relabel). Pattern "/path(/.*)?" covers dir+contents.'},
  {d:'security',q:'Allow httpd to listen on port 8080 in SELinux:',o:['setsebool -P httpd_port 8080','semanage port -a -t http_port_t -p tcp 8080','chcon -t http_port_t :8080','firewall-cmd --add-port=8080/tcp'],a:1,e:'semanage port -a -t TYPE -p PROTO PORT adds the port to SELinux policy permanently. Check current: semanage port -l | grep http.'},
  {d:'security',q:'Which makes a firewalld rule permanent AND active immediately?',o:['firewall-cmd --add-service=http --permanent','firewall-cmd --permanent --add-service=http && firewall-cmd --reload','firewall-cmd --apply --add-service=http','firewall-cmd --permanent --apply http'],a:1,e:'--permanent saves to config (survives restart). --reload applies permanent rules to running firewall. BOTH are needed for immediate+persistent.'},
  {d:'security',q:'setsebool -P httpd_can_network_connect on — what does -P do?',o:['Enables policy mode','Makes the change PERMANENT (survives reboots)','Applies to all processes','Uses permissive mode'],a:1,e:'-P = Permanent. Without -P, setsebool change is lost on reboot. Always use -P for exam tasks requiring persistence.'},
  {d:'security',q:'Where to check SELinux denials?',o:['journalctl -u selinux','ausearch -m avc -ts recent','cat /var/log/selinux','sestatus -v'],a:1,e:'ausearch -m avc -ts recent searches the audit log for recent AVC (access vector cache) denials. Pipe to audit2why for explanation.'},
  // SCRIPTING (3)
  {d:'scripting',q:'What does $? contain in bash?',o:['Current PID','Exit code of last command (0=success)','Number of arguments','Current UID'],a:1,e:'$? = exit status of last command. 0=success, non-zero=error. Critical for: if ! command; then handle_error; fi.'},
  {d:'scripting',q:'Read a file line by line in bash:',o:['for line in file; do','read -a file','while IFS= read -r line; do ... done < file','cat file | foreach line'],a:2,e:'while IFS= read -r line; do ... done < file. IFS= prevents stripping whitespace. -r prevents backslash interpretation. The correct way.'},
  {d:'scripting',q:'Check if directory /data exists in bash:',o:['if exists /data; then','if [ -d /data ]; then','if directory /data; then','if [ -e file /data ]; then'],a:1,e:'[ -d path ] = directory exists. [ -f ] = regular file. [ -e ] = any file type. [ -r ] = readable. [ -w ] = writable. [ -x ] = executable.'},
  // CONTAINERS (3)
  {d:'containers',q:'Run nginx container: background, port 8080→80, named "web":',o:['podman run nginx -p 8080:80 -d','podman run -d -p 8080:80 --name web nginx','podman start -p 8080:80 nginx','podman exec -d nginx'],a:1,e:'podman run -d (detached) -p hostPort:containerPort --name NAME image. Options come BEFORE the image name.'},
  {d:'containers',q:'Volume mount flag required for SELinux compatibility:',o:[':rw',':ro',':Z',':shared'],a:2,e:':Z tells Podman to relabel the host volume with an SELinux context the container can access. Without :Z, SELinux blocks the mount.'},
  {d:'containers',q:'Make rootless container service survive logout:',o:['systemctl enable --global webapp','loginctl enable-linger $USER','podman --persistent webapp','usermod --linger webapp'],a:1,e:'loginctl enable-linger USERNAME allows user systemd services to start at boot and persist after logout. Run as root.'},
  // BOOT (3)
  {d:'boot',q:'GRUB kernel param for root password reset:',o:['single','rescue','rd.break','init=/bin/bash'],a:2,e:'rd.break interrupts boot before transferring control to real root, giving a shell on initramfs. Append to the linux line in GRUB.'},
  {d:'boot',q:'After chroot during password reset, what file must you touch?',o:['/etc/relabel','/.autorelabel','/selinux/relabel','/tmp/relabel'],a:1,e:'touch /.autorelabel causes full SELinux filesystem relabeling on next boot. CRITICAL — skipping this causes SELinux denials.'},
  {d:'boot',q:'After editing /etc/default/grub, required command (BIOS system):',o:['grub2-update','grub2-install /dev/sda','grub2-mkconfig -o /boot/grub2/grub.cfg','update-grub'],a:2,e:'grub2-mkconfig reads /etc/default/grub and generates grub.cfg. BIOS: /boot/grub2/grub.cfg. UEFI: /boot/efi/EFI/redhat/grub.cfg.'},
];

// ── EXAM QUESTIONS (30) ──────────────────────────────────────
const EXAM_Q = [
  ...QUIZ_Q.slice(0,20),
  {d:'essentials',q:'Copy /etc to /backup preserving all permissions, timestamps, symlinks:',o:['cp -r /etc /backup','cp -a /etc /backup','cp --preserve /etc /backup','rsync /etc /backup'],a:1,e:'cp -a (archive) = -dR --preserve=all. Preserves symlinks, permissions, timestamps, ownership. Best for backup copies.'},
  {d:'users',q:'List all groups user alice belongs to:',o:['usermod -l alice','groups alice','id alice','getent group | grep alice'],a:2,e:'id alice shows UID, GID (primary), and all supplementary groups in one line. groups alice also works but shows less info.'},
  {d:'permissions',q:'Remove ALL ACL entries from file.txt:',o:['setfacl -r file.txt','setfacl -b file.txt','setfacl -x all file.txt','getfacl -d file.txt'],a:1,e:'setfacl -b (blank) removes ALL ACL entries, reverting to standard UNIX permissions. -x removes a specific entry.'},
  {d:'storage',q:'Check current swap usage:',o:['free -h','swapon --show','swapon -s','All of the above'],a:3,e:'All three work: free -h shows total/used/free mem+swap. swapon --show and swapon -s both list active swap with usage details.'},
  {d:'networking',q:'/etc/nsswitch.conf controls:',o:['DNS server addresses','Name resolution order (files vs DNS)','Firewall rules','NFS exports'],a:1,e:'/etc/nsswitch.conf defines lookup order per service type. "hosts: files dns" = check /etc/hosts first, then DNS.'},
  {d:'services',q:'Show all failed systemd units:',o:['systemctl status --failed','systemctl list-units --failed','journalctl --failed','systemctl --all failed'],a:1,e:'systemctl list-units --failed lists all units in failed state. Shortcut: systemctl --failed. Add --no-pager for scripts.'},
  {d:'software',q:'Undo the last dnf transaction:',o:['dnf revert last','dnf history undo last','dnf rollback 1','dnf undo'],a:1,e:'dnf history shows numbered transactions. dnf history undo last (or undo N) rolls back that transaction. Use with care.'},
  {d:'security',q:'Show SELinux type of /var/www/html:',o:['semanage context -l | grep html','ls -Zd /var/www/html','sestatus /var/www/html','ausearch -m context /var/www/html'],a:1,e:'ls -Zd /dir shows SELinux context of the directory itself. ls -Z /dir shows contexts of files inside. Look at the type field.'},
  {d:'scripting',q:'Correct bash if/else syntax:',o:['if command then ... fi','if [ condition ]; then ... else ... fi','if (condition): ... end','check condition ? true : false'],a:1,e:'Bash: if [ condition ]; then COMMANDS; elif ...; else COMMANDS; fi. Note the semicolons and space inside brackets.'},
  {d:'boot',q:'Switch to multi-user mode without GUI right now:',o:['systemctl switch multi-user.target','systemctl isolate multi-user.target','init 3','runlevel multi-user'],a:1,e:'systemctl isolate TARGET switches to that target immediately (stops services not in that target). set-default changes the default for next boot.'},
];

// ── LABS ─────────────────────────────────────────────────────
const LABS = [
  {
    id:'ess-1', domain:'essentials', title:'File Navigation & I/O Redirection',
    difficulty:'easy', time:15,
    objective:'Navigate the filesystem, use find/grep, master I/O redirection and pipes.',
    scenario:'New server audit. Your manager needs reports about system files.',
    tasks:[
      'Display current directory. List ALL files in /etc (including hidden) sorted by modification time.',
      'Count lines in /etc/passwd → save count to /tmp/passwd_count.txt.',
      'Find all .conf files in /etc modified in the last 7 days (suppress permission errors).',
      'Search for "root" (case-insensitive) in /etc/passwd → save to /tmp/root_lines.txt, suppress errors.',
      'Show last 10 lines of /etc/services. Count how many lines contain "tcp".',
      'Create /tmp/audit/logs/daily in one command.',
      'Copy /etc/hostname to /tmp/audit/ preserving all attributes.',
      'Create tar.gz of /tmp/audit/ → /tmp/audit_backup.tar.gz.',
    ],
    hints:[
      'pwd && ls -lath /etc | head -30',
      'wc -l /etc/passwd > /tmp/passwd_count.txt',
      'find /etc -name "*.conf" -mtime -7 2>/dev/null',
      'grep -i "root" /etc/passwd > /tmp/root_lines.txt 2>/dev/null',
      'tail -10 /etc/services && grep -c "tcp" /etc/services',
      'mkdir -p /tmp/audit/logs/daily',
      'cp -a /etc/hostname /tmp/audit/',
      'tar -czvf /tmp/audit_backup.tar.gz /tmp/audit/',
    ],
    solution:[
      {cmd:'pwd && ls -lath /etc | head -30', desc:'Current dir + sorted listing'},
      {cmd:'wc -l /etc/passwd > /tmp/passwd_count.txt && cat /tmp/passwd_count.txt', desc:'Count and save'},
      {cmd:'find /etc -name "*.conf" -mtime -7 2>/dev/null', desc:'Recent .conf files'},
      {cmd:'grep -i "root" /etc/passwd > /tmp/root_lines.txt 2>/dev/null', desc:'Search + redirect'},
      {cmd:'tail -10 /etc/services && grep -c "tcp" /etc/services', desc:'Last 10 lines + count tcp'},
      {cmd:'mkdir -p /tmp/audit/logs/daily', desc:'Create nested dirs at once'},
      {cmd:'cp -a /etc/hostname /tmp/audit/', desc:'Preserve attributes'},
      {cmd:'tar -czvf /tmp/audit_backup.tar.gz /tmp/audit/', desc:'Compressed archive'},
    ],
    validation:['cat /tmp/passwd_count.txt','ls -la /tmp/audit/','tar -tf /tmp/audit_backup.tar.gz'],
    examTip:'find, grep, and I/O redirection appear in every domain. &> redirects both stdout+stderr. >> appends. 2>/dev/null suppresses errors. Master these.',
  },
  {
    id:'ess-2', domain:'essentials', title:'vim Speed Editing',
    difficulty:'medium', time:20,
    objective:'Edit files in vim — the primary and often only editor available during the RHCSA exam.',
    scenario:'All exam tasks require editing config files. vim fluency = exam marks.',
    tasks:[
      'Create /tmp/myconfig.txt with vim. Write 10 lines (any content). Save and quit.',
      'Reopen. Enable line numbers (:set number). Go to line 6. Delete that line. Save.',
      'Reopen. Add "# RHCSA CONFIG" at the very top of the file.',
      'Globally replace every "test" with "production" in the file.',
      'Copy lines 2-4 and paste them at the end of the file.',
      'Open /etc/passwd read-only, find "root", note its line number, quit without saving.',
      'Create /tmp/myscript.sh with shebang #!/bin/bash and echo "Hello RHCSA".',
      'Extract first 20 lines of /etc/ssh/sshd_config to /tmp/sshd_head.conf.',
    ],
    hints:[
      'vim /tmp/myconfig.txt → i → type → Esc → :wq',
      ':set number → :6 → dd → :wq',
      'gg → O → type text → Esc → :wq',
      ':%s/test/production/g → :wq',
      ':2,4y → G → p → :wq',
      'vim -R /etc/passwd → /root → :set number → :q',
      'vim /tmp/myscript.sh → i → shebang+echo → Esc → :wq',
      'head -n 20 /etc/ssh/sshd_config > /tmp/sshd_head.conf',
    ],
    solution:[
      {cmd:'vim /tmp/myconfig.txt  # i → type 10 lines → Esc → :wq', desc:'Create and save'},
      {cmd:'vim /tmp/myconfig.txt  # :set number → :6 → dd → :wq', desc:'Delete line 6'},
      {cmd:'vim /tmp/myconfig.txt  # gg → O → "# RHCSA CONFIG" → Esc → :wq', desc:'Insert at top'},
      {cmd:'vim /tmp/myconfig.txt  # :%s/test/production/g → :wq', desc:'Global replace'},
      {cmd:'vim /tmp/myconfig.txt  # :2,4y → G → p → :wq', desc:'Yank range, paste at end'},
      {cmd:'vim -R /etc/passwd  # /root → :set number → :q', desc:'Read-only, find, quit'},
      {cmd:'printf "#!/bin/bash\\necho \\"Hello RHCSA\\"\\n" > /tmp/myscript.sh', desc:'Create script'},
      {cmd:'head -n 20 /etc/ssh/sshd_config > /tmp/sshd_head.conf', desc:'Extract first 20 lines'},
    ],
    validation:['cat /tmp/myconfig.txt','wc -l /tmp/sshd_head.conf','head -1 /tmp/myscript.sh'],
    examTip:'Know cold: :wq :q! :%s/old/new/g dd yy p G gg /search n N :set number :N (go to line N). visudo uses vim. Practice daily.',
  },
  {
    id:'usr-1', domain:'users', title:'User & Group Environment',
    difficulty:'medium', time:25,
    objective:'Create users/groups with UIDs/GIDs, manage passwords, aging, and account locking.',
    scenario:'Set up a development server with structured team access.',
    tasks:[
      'Create groups: developers (GID 3000), qa (GID 3001), devops (GID 3002).',
      'Create alice: UID 2001, home /home/alice, shell /bin/bash, primary group developers.',
      'Create bob: UID 2002, home /home/bob, shell /bin/bash, primary group qa.',
      'Add alice and bob to devops as supplementary members (keep primary groups).',
      'Set alice\'s password. Force password change on next login.',
      'Set bob\'s account to expire on 2026-12-31. Set max password age to 60 days.',
      'Lock charlie\'s account (create charlie first if needed). Verify with passwd -S.',
      'Create system account "webrunner": no home, shell /sbin/nologin.',
    ],
    hints:[
      'groupadd -g 3000 developers && groupadd -g 3001 qa && groupadd -g 3002 devops',
      'useradd -u 2001 -m -s /bin/bash -g developers alice',
      'useradd -u 2002 -m -s /bin/bash -g qa bob',
      'usermod -aG devops alice && usermod -aG devops bob',
      'passwd alice && chage -d 0 alice',
      'chage -E 2026-12-31 bob && chage -M 60 bob',
      'useradd -m charlie 2>/dev/null; usermod -L charlie && passwd -S charlie',
      'useradd -r -s /sbin/nologin webrunner',
    ],
    solution:[
      {cmd:'groupadd -g 3000 developers && groupadd -g 3001 qa && groupadd -g 3002 devops', desc:'Create groups'},
      {cmd:'useradd -u 2001 -m -s /bin/bash -g developers alice', desc:'Create alice'},
      {cmd:'useradd -u 2002 -m -s /bin/bash -g qa bob', desc:'Create bob'},
      {cmd:'usermod -aG devops alice && usermod -aG devops bob', desc:'Add to devops (keep existing groups!)'},
      {cmd:'echo "Password1!" | passwd --stdin alice 2>/dev/null || passwd alice && chage -d 0 alice', desc:'Set password, force change'},
      {cmd:'chage -E 2026-12-31 bob && chage -M 60 bob', desc:'Account expiry + password max age'},
      {cmd:'useradd -m charlie 2>/dev/null; usermod -L charlie && passwd -S charlie', desc:'Lock account'},
      {cmd:'useradd -r -s /sbin/nologin webrunner', desc:'System account'},
    ],
    validation:['id alice','id bob','grep devops /etc/group','chage -l alice','getent passwd webrunner'],
    examTip:'TRAP: usermod -G devs (no -a) = REPLACE all supplementary groups. Always -aG. System account (-r) has UID < 1000. chage -d 0 = force password change.',
  },
  {
    id:'perm-1', domain:'permissions', title:'Permissions, Special Bits & ACL',
    difficulty:'medium', time:25,
    objective:'Standard permissions, SUID/SGID/Sticky, and fine-grained ACL configuration.',
    scenario:'Create a shared collaborative directory for a dev team with correct access control.',
    tasks:[
      'Create /opt/devshared owned root:developers. Set permissions: rwxrws--- (SGID).',
      'Add sticky bit to /opt/devshared.',
      'Verify with ls -ld (should show drwxrws--T).',
      'Give charlie (not in developers) read+execute access via ACL.',
      'Set default ACL: new files in /opt/devshared get developers group rw access automatically.',
      'As alice, create a file in /opt/devshared. Verify its group is "developers" (SGID works).',
      'View full ACL with getfacl /opt/devshared.',
      'Remove charlie\'s ACL entry. Verify he can no longer access.',
    ],
    hints:[
      'mkdir /opt/devshared && chown root:developers /opt/devshared && chmod 2770 /opt/devshared',
      'chmod +t /opt/devshared  →  full: chmod 3770 /opt/devshared',
      'ls -ld /opt/devshared',
      'setfacl -m u:charlie:r-x /opt/devshared',
      'setfacl -d -m g:developers:rw- /opt/devshared',
      'su - alice -c "touch /opt/devshared/test.txt" && ls -la /opt/devshared/',
      'getfacl /opt/devshared',
      'setfacl -x u:charlie /opt/devshared && getfacl /opt/devshared',
    ],
    solution:[
      {cmd:'mkdir /opt/devshared && chown root:developers /opt/devshared && chmod 2770 /opt/devshared', desc:'Create + SGID'},
      {cmd:'chmod +t /opt/devshared', desc:'Add sticky bit'},
      {cmd:'ls -ld /opt/devshared', desc:'Verify drwxrws--T'},
      {cmd:'setfacl -m u:charlie:r-x /opt/devshared', desc:'ACL read-only for charlie'},
      {cmd:'setfacl -d -m g:developers:rw- /opt/devshared', desc:'Default ACL for new files'},
      {cmd:'su - alice -c "touch /opt/devshared/alice.txt" 2>/dev/null && ls -la /opt/devshared/', desc:'Test SGID'},
      {cmd:'getfacl /opt/devshared', desc:'View full ACL'},
      {cmd:'setfacl -x u:charlie /opt/devshared', desc:'Remove charlie ACL'},
    ],
    validation:['ls -ld /opt/devshared','getfacl /opt/devshared'],
    examTip:'chmod 3770 = SGID(2000)+Sticky(1000)+770. SGID on dir = new files inherit group. Sticky = only owner deletes own files. Perfect collaborative dir pattern.',
  },
  {
    id:'str-1', domain:'storage', title:'LVM End-to-End Workflow',
    difficulty:'hard', time:40,
    objective:'Partition disk, create LVM, format XFS, mount persistently, extend online.',
    scenario:'New disk /dev/sdb (or /dev/vdb). Create LVM setup for application data.',
    tasks:[
      'Confirm the new disk: lsblk. Note device name.',
      'Create one partition on /dev/sdb using the entire disk. Type: Linux LVM (8e). Notify kernel.',
      'Initialize partition as Physical Volume.',
      'Create Volume Group "appvg" from the PV.',
      'Create Logical Volume "appdata" of 5GB.',
      'Create XFS filesystem on the LV.',
      'Create /var/app/data. Mount LV there. Add UUID-based fstab entry.',
      'Test fstab: umount /var/app/data && mount -a. Verify with df -h.',
      'Extend appdata by 2GB. Grow XFS filesystem online (do not unmount).',
      'Create 512MB swap file. Activate it. Add to fstab.',
    ],
    hints:[
      'lsblk',
      'fdisk /dev/sdb → n,p,1,Enter,Enter,t,8e,w → partprobe /dev/sdb',
      'pvcreate /dev/sdb1',
      'vgcreate appvg /dev/sdb1',
      'lvcreate -L 5G -n appdata appvg',
      'mkfs.xfs /dev/appvg/appdata',
      'mkdir -p /var/app/data && mount /dev/appvg/appdata /var/app/data && UUID=$(blkid -s UUID -o value /dev/appvg/appdata) && echo "UUID=$UUID /var/app/data xfs defaults 0 0" >> /etc/fstab',
      'umount /var/app/data && mount -a && df -h /var/app/data',
      'lvextend -L +2G /dev/appvg/appdata && xfs_growfs /var/app/data',
      'dd if=/dev/zero of=/swapfile bs=1M count=512 && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && echo "/swapfile swap swap defaults 0 0" >> /etc/fstab',
    ],
    solution:[
      {cmd:'lsblk', desc:'Identify new disk'},
      {cmd:'fdisk /dev/sdb  # n→p→1→Enter→Enter→t→8e→w', desc:'Partition'},
      {cmd:'partprobe /dev/sdb && lsblk', desc:'Notify kernel'},
      {cmd:'pvcreate /dev/sdb1', desc:'Init PV'},
      {cmd:'vgcreate appvg /dev/sdb1', desc:'Create VG'},
      {cmd:'lvcreate -L 5G -n appdata appvg', desc:'Create 5GB LV'},
      {cmd:'mkfs.xfs /dev/appvg/appdata', desc:'Format XFS'},
      {cmd:'mkdir -p /var/app/data && mount /dev/appvg/appdata /var/app/data', desc:'Mount'},
      {cmd:'echo "UUID=$(blkid -s UUID -o value /dev/appvg/appdata)  /var/app/data  xfs  defaults  0 0" >> /etc/fstab', desc:'fstab entry'},
      {cmd:'mount -a && df -h /var/app/data', desc:'Test fstab'},
      {cmd:'lvextend -L +2G /dev/appvg/appdata && xfs_growfs /var/app/data', desc:'Extend LV + grow FS online'},
      {cmd:'dd if=/dev/zero of=/swapfile bs=1M count=512 status=progress && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile', desc:'Swap file'},
      {cmd:'echo "/swapfile swap swap defaults 0 0" >> /etc/fstab && swapon --show', desc:'Persist swap'},
    ],
    validation:['pvs && vgs && lvs','df -h /var/app/data','grep appdata /etc/fstab','swapon --show'],
    examTip:'LVM ~20% of exam. XFS grows ONLINE but CANNOT shrink. Always use UUID in fstab. After lvextend: xfs_growfs (XFS) or resize2fs (ext4). Swap file needs chmod 600!',
  },
  {
    id:'proc-1', domain:'processes', title:'Process Control & Job Scheduling',
    difficulty:'medium', time:25,
    objective:'Monitor processes, control priority, schedule cron and at jobs.',
    scenario:'Production server management: identify resource hogs, schedule maintenance.',
    tasks:[
      'Show all processes sorted by CPU usage (top 15). Then top 10 by memory.',
      'Find PID(s) of sshd using pgrep. Send SIGHUP (reload) to the main sshd process.',
      'Start "sleep 600" in background. List jobs. Suspend it. Send to background.',
      'Run a tar backup with nice level 15 in background: tar czf /tmp/etc_bk.tar.gz /etc',
      'Change running process nice to 5 using renice.',
      'Create cron job for root: delete /tmp files older than 7 days, daily at 3:15 AM.',
      'Create cron job: df -h >> /var/log/disk_usage.log every Monday at 7 AM.',
      'Schedule a one-time job: write "Maintenance done" to /tmp/maint.log in 3 minutes.',
      'Create /usr/local/bin/cleanup.sh that removes files >30 days old from /tmp. Make executable.',
      'Verify: crontab -l, atq, ls -la /usr/local/bin/cleanup.sh.',
    ],
    hints:[
      'ps aux --sort=-%cpu | head -16 && ps aux --sort=-%mem | head -11',
      'pgrep -x sshd && kill -HUP $(pgrep -x sshd | head -1)',
      'sleep 600 & && jobs → fg %1 → Ctrl+Z → bg %1',
      'nice -n 15 tar czf /tmp/etc_bk.tar.gz /etc 2>/dev/null &',
      'renice -n 5 -p PID (use PID from step 4)',
      'crontab -e → 15 3 * * * find /tmp -type f -mtime +7 -delete',
      '0 7 * * 1 /usr/bin/df -h >> /var/log/disk_usage.log',
      'echo "echo Maintenance done >> /tmp/maint.log" | at now + 3 minutes',
      'printf "#!/bin/bash\\nfind /tmp -type f -mtime +30 -delete\\n" > /usr/local/bin/cleanup.sh && chmod +x /usr/local/bin/cleanup.sh',
      'crontab -l && atq && ls -la /usr/local/bin/cleanup.sh',
    ],
    solution:[
      {cmd:'ps aux --sort=-%cpu | head -16', desc:'Top CPU consumers'},
      {cmd:'ps aux --sort=-%mem | head -11', desc:'Top memory consumers'},
      {cmd:'pgrep -x sshd && kill -HUP $(pgrep -x sshd | head -1)', desc:'Find sshd, send HUP'},
      {cmd:'sleep 600 & && jobs', desc:'Background job + list'},
      {cmd:'nice -n 15 tar czf /tmp/etc_bk.tar.gz /etc 2>/dev/null &', desc:'Low priority tar'},
      {cmd:'# crontab -e:\n15 3 * * * find /tmp -type f -mtime +7 -delete', desc:'Daily cleanup cron'},
      {cmd:'# crontab -e:\n0 7 * * 1 /usr/bin/df -h >> /var/log/disk_usage.log', desc:'Weekly disk log'},
      {cmd:'echo "echo Maintenance done >> /tmp/maint.log" | at now + 3 minutes', desc:'One-time at job'},
      {cmd:'printf "#!/bin/bash\\nfind /tmp -type f -mtime +30 -delete\\n" > /usr/local/bin/cleanup.sh && chmod +x /usr/local/bin/cleanup.sh', desc:'Cleanup script'},
    ],
    validation:['crontab -l','atq','cat /usr/local/bin/cleanup.sh','ls -la /usr/local/bin/cleanup.sh'],
    examTip:'Cron: MIN HOUR DOM MON DOW. Use full paths. nice: -20=max, 19=min priority. renice changes running. nohup = survive logout. at = one-time only.',
  },
  {
    id:'net-1', domain:'networking', title:'Static Network Configuration',
    difficulty:'medium', time:20,
    objective:'Configure static IP, gateway, DNS, hostname persistently using nmcli.',
    scenario:'Server needs static IP before going to production.',
    tasks:[
      'List all network interfaces and connection names.',
      'Set hostname to "rhcsa-lab.example.com" permanently.',
      'Configure static IP 192.168.100.10/24 on main interface.',
      'Set default gateway 192.168.100.1.',
      'Set DNS servers to 8.8.8.8 and 8.8.4.4.',
      'Switch connection method to manual (static).',
      'Apply configuration: bring connection down and up.',
      'Verify: ip addr show, ip route show.',
      'Add /etc/hosts entry: 192.168.100.200 → db.example.com db.',
      'Test DNS resolution with dig or nslookup.',
    ],
    hints:[
      'nmcli device status && nmcli connection show',
      'hostnamectl set-hostname rhcsa-lab.example.com',
      'CON=$(nmcli -t -f NAME connection show --active | head -1); nmcli con mod "$CON" ipv4.addresses "192.168.100.10/24"',
      'nmcli con mod "$CON" ipv4.gateway "192.168.100.1"',
      'nmcli con mod "$CON" ipv4.dns "8.8.8.8 8.8.4.4"',
      'nmcli con mod "$CON" ipv4.method manual',
      'nmcli con up "$CON"',
      'ip addr show && ip route show',
      'echo "192.168.100.200 db.example.com db" >> /etc/hosts',
      'dig google.com @8.8.8.8 || nslookup google.com',
    ],
    solution:[
      {cmd:'nmcli device status && nmcli connection show', desc:'List interfaces'},
      {cmd:'CON=$(nmcli -t -f NAME connection show --active | head -1) && echo "Connection: $CON"', desc:'Get connection name'},
      {cmd:'hostnamectl set-hostname rhcsa-lab.example.com', desc:'Set hostname'},
      {cmd:'nmcli con mod "$CON" ipv4.addresses "192.168.100.10/24" ipv4.gateway "192.168.100.1" ipv4.dns "8.8.8.8 8.8.4.4" ipv4.method manual', desc:'Configure static IP (all at once)'},
      {cmd:'nmcli con up "$CON"', desc:'Apply settings'},
      {cmd:'ip addr show && ip route show', desc:'Verify'},
      {cmd:'echo "192.168.100.200 db.example.com db" >> /etc/hosts && cat /etc/hosts', desc:'/etc/hosts entry'},
    ],
    validation:['ip addr show','ip route show','hostnamectl','cat /etc/hosts | grep db'],
    examTip:'Replace connection name with actual name from nmcli con show. After modify, MUST run nmcli con up. Never edit NM connection files directly.',
  },
  {
    id:'svc-1', domain:'services', title:'Services, Units & Timers',
    difficulty:'medium', time:25,
    objective:'Manage services with systemctl, analyze with journalctl, create custom unit and timer.',
    scenario:'Deploy httpd and create a disk monitoring service that runs every 5 minutes.',
    tasks:[
      'Install httpd. Enable and start in one command. Verify running on port 80.',
      'View last 30 log entries for httpd. Follow live for 5 seconds (Ctrl+C).',
      'Restart httpd. View post-restart logs.',
      'Create /usr/local/bin/diskmon.sh: appends timestamp + df -h / to /var/log/diskmon.log.',
      'Create /etc/systemd/system/diskmon.service (Type=oneshot).',
      'daemon-reload, enable --now diskmon.service. Check /var/log/diskmon.log.',
      'Create /etc/systemd/system/diskmon.timer (every 5 minutes).',
      'daemon-reload, enable --now diskmon.timer. List timers.',
      'Change default target to multi-user.target.',
      'Show all failed systemd units.',
    ],
    hints:[
      'dnf install -y httpd && systemctl enable --now httpd && ss -tlnp | grep :80',
      'journalctl -u httpd -n 30 && journalctl -u httpd -f',
      'systemctl restart httpd && journalctl -u httpd -n 5',
      'printf "#!/bin/bash\\necho \\"$(date): $(df -h / | tail -1)\\" >> /var/log/diskmon.log\\n" > /usr/local/bin/diskmon.sh && chmod +x ...',
      '[Unit] After=network.target [Service] Type=oneshot ExecStart=/usr/local/bin/diskmon.sh [Install] WantedBy=multi-user.target',
      'systemctl daemon-reload && systemctl enable --now diskmon.service && cat /var/log/diskmon.log',
      '[Unit] [Timer] OnBootSec=1min OnUnitActiveSec=5min [Install] WantedBy=timers.target',
      'systemctl daemon-reload && systemctl enable --now diskmon.timer && systemctl list-timers',
      'systemctl set-default multi-user.target',
      'systemctl list-units --failed',
    ],
    solution:[
      {cmd:'dnf install -y httpd && systemctl enable --now httpd', desc:'Install, enable, start'},
      {cmd:'journalctl -u httpd -n 30', desc:'Last 30 entries'},
      {cmd:'systemctl restart httpd && journalctl -u httpd -n 5', desc:'Restart + check log'},
      {cmd:"printf '#!/bin/bash\\necho \"$(date): $(df -h / | tail -1)\" >> /var/log/diskmon.log\\n' > /usr/local/bin/diskmon.sh && chmod +x /usr/local/bin/diskmon.sh", desc:'Monitoring script'},
      {cmd:"cat > /etc/systemd/system/diskmon.service << 'EOF'\n[Unit]\nDescription=Disk Monitor\nAfter=network.target\n[Service]\nType=oneshot\nExecStart=/usr/local/bin/diskmon.sh\n[Install]\nWantedBy=multi-user.target\nEOF", desc:'Service unit file'},
      {cmd:'systemctl daemon-reload && systemctl enable --now diskmon.service && cat /var/log/diskmon.log', desc:'Reload, enable, verify'},
      {cmd:"cat > /etc/systemd/system/diskmon.timer << 'EOF'\n[Unit]\nDescription=Diskmon timer - every 5 min\n[Timer]\nOnBootSec=1min\nOnUnitActiveSec=5min\n[Install]\nWantedBy=timers.target\nEOF", desc:'Timer unit file'},
      {cmd:'systemctl daemon-reload && systemctl enable --now diskmon.timer && systemctl list-timers', desc:'Enable timer'},
      {cmd:'systemctl set-default multi-user.target && systemctl get-default', desc:'Change default target'},
      {cmd:'systemctl list-units --failed', desc:'Show failed units'},
    ],
    validation:['systemctl status httpd','systemctl status diskmon.service','systemctl list-timers','cat /var/log/diskmon.log'],
    examTip:'daemon-reload is REQUIRED after creating/editing unit files. enable --now = enable+start. Timer needs both .service and .timer. journalctl -u UNIT -f follows live.',
  },
  {
    id:'sw-1', domain:'software', title:'Package Management & Repositories',
    difficulty:'medium', time:20,
    objective:'Install software, manage repos, use modules, query RPM database.',
    scenario:'Set up LAMP server using dnf. Configure local repo. Use modules for versioned packages.',
    tasks:[
      'Install httpd, mariadb-server, and php in one command.',
      'Find which package provides /usr/bin/semanage. Install it.',
      'List all files installed by the httpd package (first 15 only).',
      'Verify integrity of httpd package files.',
      'Create local repo /etc/yum.repos.d/local.repo pointing to file:///repo.',
      'List enabled repos. Disable then re-enable local repo.',
      'List available Node.js module streams. Enable nodejs:18, install nodejs.',
      'Show last 5 dnf transactions.',
      'Find which package provides sealert.',
      'Show all packages whose names start with "python3" (installed + available).',
    ],
    hints:[
      'dnf install -y httpd mariadb-server php',
      'dnf whatprovides semanage → dnf install -y policycoreutils-python-utils',
      'rpm -ql httpd | head -15',
      'rpm -V httpd',
      '[local] name=Local Repo baseurl=file:///repo enabled=1 gpgcheck=0',
      'dnf repolist && dnf config-manager --disable local && dnf config-manager --enable local',
      'dnf module list nodejs && dnf module enable nodejs:18 -y && dnf install nodejs -y',
      'dnf history | head -6',
      'dnf whatprovides sealert',
      'dnf list python3* 2>/dev/null | head -20',
    ],
    solution:[
      {cmd:'dnf install -y httpd mariadb-server php', desc:'Install LAMP stack'},
      {cmd:'dnf whatprovides semanage && dnf install -y policycoreutils-python-utils', desc:'Find and install semanage provider'},
      {cmd:'rpm -ql httpd | head -15', desc:'List httpd files (first 15)'},
      {cmd:'rpm -V httpd', desc:'Verify integrity (empty output = OK)'},
      {cmd:"cat > /etc/yum.repos.d/local.repo << 'EOF'\n[local]\nname=Local Repository\nbaseurl=file:///repo\nenabled=1\ngpgcheck=0\nEOF", desc:'Local repo config'},
      {cmd:'dnf repolist && dnf config-manager --disable local && dnf repolist && dnf config-manager --enable local', desc:'List/disable/enable repo'},
      {cmd:'dnf module list nodejs && dnf module enable nodejs:18 -y && dnf install nodejs -y', desc:'Module enable + install'},
      {cmd:'dnf history | head -6', desc:'Transaction history'},
      {cmd:'dnf whatprovides sealert', desc:'Find sealert package'},
      {cmd:'dnf list python3* 2>/dev/null | head -20', desc:'List python3 packages'},
    ],
    validation:['rpm -q httpd mariadb-server','dnf repolist','cat /etc/yum.repos.d/local.repo'],
    examTip:'"dnf whatprovides" is exam-critical. Also: rpm -qf /path (which package owns file). Module pattern: list → enable → install. Always use full paths for binaries.',
  },
  {
    id:'sec-1', domain:'security', title:'SELinux Fix & Firewall Rules',
    difficulty:'hard', time:30,
    objective:'Fix SELinux denials by relabeling, managing ports and booleans. Configure firewalld zones.',
    scenario:'Apache must serve from /webdata. SELinux blocks it. Fix without disabling SELinux.',
    tasks:[
      'Install httpd. Create /webdata/index.html with "RHCSA SELinux Lab".',
      'Set Apache DocumentRoot to /webdata. Start httpd. Confirm 403 (SELinux blocks).',
      'Confirm SELinux is ENFORCING. Do NOT set Permissive.',
      'Compare contexts: ls -Zd /webdata vs /var/www/html.',
      'Check audit log for the AVC denial. Pipe to audit2why.',
      'Add permanent SELinux context rule for /webdata. Apply with restorecon.',
      'Test: curl http://localhost should now return "RHCSA SELinux Lab".',
      'Enable httpd_can_network_connect boolean permanently.',
      'Add port 8080/tcp to http_port_t. Add Listen 8080 to httpd.conf. Restart httpd.',
      'Allow http+https in firewalld public zone permanently. Open 8080/tcp. Reload.',
    ],
    hints:[
      'dnf install -y httpd && mkdir /webdata && echo "RHCSA SELinux Lab" > /webdata/index.html',
      "sed -i 's|DocumentRoot \"/var/www/html\"|DocumentRoot \"/webdata\"|' /etc/httpd/conf/httpd.conf && systemctl start httpd && curl http://localhost",
      'getenforce  # must be Enforcing',
      'ls -Zd /webdata && ls -Zd /var/www/html',
      'ausearch -m avc -ts recent 2>/dev/null | audit2why',
      'semanage fcontext -a -t httpd_sys_content_t "/webdata(/.*)?" && restorecon -Rv /webdata',
      'curl http://localhost',
      'setsebool -P httpd_can_network_connect on',
      'semanage port -a -t http_port_t -p tcp 8080 && echo "Listen 8080" >> /etc/httpd/conf/httpd.conf && systemctl restart httpd',
      'firewall-cmd --permanent --add-service=http --add-service=https && firewall-cmd --permanent --add-port=8080/tcp && firewall-cmd --reload',
    ],
    solution:[
      {cmd:'dnf install -y httpd && mkdir -p /webdata && echo "RHCSA SELinux Lab" > /webdata/index.html', desc:'Setup'},
      {cmd:"sed -i 's|DocumentRoot \"/var/www/html\"|DocumentRoot \"/webdata\"|' /etc/httpd/conf/httpd.conf && systemctl start httpd", desc:'Change DocumentRoot'},
      {cmd:'getenforce', desc:'Confirm Enforcing'},
      {cmd:'ls -Zd /webdata /var/www/html', desc:'Compare SELinux contexts'},
      {cmd:'ausearch -m avc -ts recent 2>/dev/null | audit2why 2>/dev/null | tail -20', desc:'View denial + explanation'},
      {cmd:'semanage fcontext -a -t httpd_sys_content_t "/webdata(/.*)?"', desc:'Add permanent context rule'},
      {cmd:'restorecon -Rv /webdata && curl http://localhost', desc:'Apply and test'},
      {cmd:'setsebool -P httpd_can_network_connect on && getsebool httpd_can_network_connect', desc:'Enable boolean permanently'},
      {cmd:'semanage port -a -t http_port_t -p tcp 8080 && echo "Listen 8080" >> /etc/httpd/conf/httpd.conf && systemctl restart httpd', desc:'Allow port 8080'},
      {cmd:'firewall-cmd --permanent --add-service=http --add-service=https && firewall-cmd --permanent --add-port=8080/tcp && firewall-cmd --reload', desc:'Firewall rules'},
    ],
    validation:['getenforce','curl http://localhost','semanage port -l | grep 8080','firewall-cmd --list-all'],
    examTip:'NEVER disable SELinux in the exam. semanage+restorecon = permanent fix. chcon = temporary. Pattern "/path(/.*)?" covers dir AND all files inside. -P for permanent booleans.',
  },
  {
    id:'scr-1', domain:'scripting', title:'Bash Scripting for Sysadmin',
    difficulty:'medium', time:30,
    objective:'Write practical bash scripts with variables, loops, conditionals, functions, error handling.',
    scenario:'Automate common sysadmin tasks: user provisioning, health checks, log analysis.',
    tasks:[
      'Write /usr/local/bin/create_user.sh: args=username,group. Creates user if not exist, adds to group, sets "ChangeMe!" password. Exits 1 if no args.',
      'Write /usr/local/bin/svc_check.sh: arg=service. Checks if running, starts if not. Logs to /var/log/svc_check.log with timestamp.',
      'Write /usr/local/bin/disk_alert.sh: arg=threshold%. Warns if any mountpoint exceeds threshold. Default 80%.',
      'Write /usr/local/bin/batch_users.sh: reads /tmp/users.csv (user,group per line), creates each user. Skip if exists. Print summary.',
      'Test all scripts. Fix any errors.',
      'Schedule disk_alert.sh every hour via cron for root.',
    ],
    hints:[
      '[ $# -lt 2 ] && echo "Usage: $0 user group" && exit 1',
      'systemctl is-active "$1" || systemctl start "$1"',
      'df -h | awk \'NR>1 && $5+0 > threshold {print "WARN:", $6, "is", $5}\'',
      'while IFS=, read -r user grp; do id "$user" &>/dev/null && continue; useradd ...; done < /tmp/users.csv',
      'bash -n script.sh (syntax check)',
      '0 * * * * /usr/local/bin/disk_alert.sh >> /var/log/disk_alert.log 2>&1',
    ],
    solution:[
      {cmd:"cat > /usr/local/bin/create_user.sh << 'SCRIPT'\n#!/bin/bash\n[ $# -lt 2 ] && echo \"Usage: $0 username group\" && exit 1\nUSER=\"$1\"; GRP=\"$2\"\nid \"$USER\" &>/dev/null && echo \"[SKIP] $USER exists\" && exit 0\ngroupadd \"$GRP\" 2>/dev/null\nuseradd -m -G \"$GRP\" \"$USER\" && echo \"ChangeMe!\" | passwd --stdin \"$USER\" &>/dev/null\necho \"[OK] Created $USER in $GRP\"\nSCRIPT\nchmod +x /usr/local/bin/create_user.sh", desc:'User creation script'},
      {cmd:"cat > /usr/local/bin/svc_check.sh << 'SCRIPT'\n#!/bin/bash\n[ -z \"$1\" ] && echo \"Usage: $0 service\" && exit 1\nSVC=\"$1\"; LOG=/var/log/svc_check.log\nif ! systemctl is-active \"$SVC\" &>/dev/null; then\n  systemctl start \"$SVC\" 2>/dev/null && STATUS=RESTARTED || STATUS=FAILED\nelse\n  STATUS=RUNNING\nfi\necho \"$(date '+%Y-%m-%d %H:%M:%S'): $SVC - $STATUS\" | tee -a \"$LOG\"\nSCRIPT\nchmod +x /usr/local/bin/svc_check.sh", desc:'Service check script'},
      {cmd:"cat > /usr/local/bin/disk_alert.sh << 'SCRIPT'\n#!/bin/bash\nTHRESH=${1:-80}\ndf -h | awk -v t=\"$THRESH\" 'NR>1 {gsub(/%/,\"\",$5); if($5+0>=t) print \"WARN:\", $6, \"is\", $5\"%\"}'\nSCRIPT\nchmod +x /usr/local/bin/disk_alert.sh", desc:'Disk alert script'},
      {cmd:"printf 'alice,developers\\nbob,qa\\ncharlie,devops\\n' > /tmp/users.csv\ncat > /usr/local/bin/batch_users.sh << 'SCRIPT'\n#!/bin/bash\nCREATED=0; SKIPPED=0\nwhile IFS=, read -r user grp; do\n  [ -z \"$user\" ] && continue\n  if id \"$user\" &>/dev/null; then echo \"[SKIP] $user\"; ((SKIPPED++)); continue; fi\n  groupadd \"$grp\" 2>/dev/null\n  useradd -m -G \"$grp\" \"$user\" && ((CREATED++)) && echo \"[OK] $user\"\ndone < /tmp/users.csv\necho \"Summary: $CREATED created, $SKIPPED skipped\"\nSCRIPT\nchmod +x /usr/local/bin/batch_users.sh", desc:'Batch user creation'},
      {cmd:'bash -n /usr/local/bin/create_user.sh && bash -n /usr/local/bin/svc_check.sh && echo "Syntax OK"', desc:'Test syntax'},
      {cmd:'# crontab -e:\n0 * * * * /usr/local/bin/disk_alert.sh >> /var/log/disk_alert.log 2>&1', desc:'Schedule hourly'},
    ],
    validation:['ls -la /usr/local/bin/*.sh','bash -n /usr/local/bin/create_user.sh','crontab -l | grep disk'],
    examTip:'Exam scripts are usually simple: read file, create resources, check conditions. Key vars: $# $1 $2 $? $@. while IFS= read -r line reads files. Always use full command paths.',
  },
  {
    id:'con-1', domain:'containers', title:'Rootless Podman Containers',
    difficulty:'medium', time:25,
    objective:'Deploy containers as non-root user, manage volumes, configure as persistent systemd service.',
    scenario:'Deploy nginx as a rootless container that starts automatically without root.',
    tasks:[
      'Install podman. Pull nginx image as root.',
      'Create user "appuser" with home dir.',
      'As appuser: run nginx container named "myapp", port 9090→80, detached.',
      'Create ~/webroot/index.html with "Hello from RHCSA Container".',
      'Stop and remove myapp. Re-run with ~/webroot mounted to /usr/share/nginx/html:Z.',
      'Test: curl localhost:9090.',
      'Generate systemd unit file for myapp container.',
      'Install unit, daemon-reload, enable --now as user service.',
      'As root: enable lingering for appuser.',
      'Stop container. Verify systemd restarts it automatically.',
    ],
    hints:[
      'dnf install -y podman && podman pull docker.io/library/nginx',
      'useradd -m appuser && su - appuser',
      'podman run -d --name myapp -p 9090:80 nginx',
      'mkdir -p ~/webroot && echo "<h1>Hello from RHCSA Container</h1>" > ~/webroot/index.html',
      'podman stop myapp && podman rm myapp && podman run -d --name myapp -p 9090:80 -v ~/webroot:/usr/share/nginx/html:Z nginx',
      'curl localhost:9090',
      'mkdir -p ~/.config/systemd/user && cd ~/.config/systemd/user && podman generate systemd --name myapp --files --new',
      'systemctl --user daemon-reload && systemctl --user enable --now container-myapp.service',
      'exit (back to root) && loginctl enable-linger appuser',
      'su - appuser -c "podman stop myapp; sleep 3; systemctl --user status container-myapp"',
    ],
    solution:[
      {cmd:'dnf install -y podman && podman pull docker.io/library/nginx', desc:'Install podman, pull image'},
      {cmd:'useradd -m appuser && su - appuser', desc:'Switch to non-root user'},
      {cmd:'podman run -d --name myapp -p 9090:80 nginx && podman ps', desc:'Run container'},
      {cmd:'mkdir -p ~/webroot && echo "<h1>Hello from RHCSA Container</h1>" > ~/webroot/index.html', desc:'Create web content'},
      {cmd:'podman stop myapp && podman rm myapp && podman run -d --name myapp -p 9090:80 -v ~/webroot:/usr/share/nginx/html:Z nginx', desc:'Re-run with volume'},
      {cmd:'curl localhost:9090', desc:'Test access'},
      {cmd:'mkdir -p ~/.config/systemd/user && cd ~/.config/systemd/user && podman generate systemd --name myapp --files --new', desc:'Generate systemd unit'},
      {cmd:'systemctl --user daemon-reload && systemctl --user enable --now container-myapp.service', desc:'Enable as user service'},
      {cmd:'exit && loginctl enable-linger appuser', desc:'Enable lingering (as root)'},
      {cmd:'su - appuser -c "systemctl --user status container-myapp.service"', desc:'Verify'},
    ],
    validation:['podman ps','curl localhost:9090','loginctl show-user appuser | grep Linger'],
    examTip:':Z on volumes = SELinux relabel for container. loginctl enable-linger = survive logout. --new flag in generate systemd = unit manages container lifecycle. systemctl --user for user services.',
  },
  {
    id:'boot-1', domain:'boot', title:'Boot Management & System Recovery',
    difficulty:'hard', time:30,
    objective:'Reset root password, configure GRUB2, manage targets, troubleshoot boot issues.',
    scenario:'Lost root access. Recover the system. Configure GRUB. Fix a bad fstab.',
    tasks:[
      'Show current default boot target. Change it to multi-user.target.',
      'Check BIOS or UEFI. Set GRUB timeout to 3 seconds.',
      'Regenerate GRUB config to apply the timeout change.',
      'Add "ipv6.disable=1" to GRUB_CMDLINE_LINUX. Regenerate GRUB.',
      'Simulate bad fstab: add fake entry. Run mount -a (see error). Fix it.',
      'ROOT PASSWORD RESET: reboot → GRUB edit → rd.break → remount → chroot → passwd → autorelabel → exit.',
      'Create httpd service override: increase TimeoutStartSec to 90 seconds.',
      'Show how to reach emergency target from running system.',
      'Verify kernel params are applied: cat /proc/cmdline.',
      'Check what services depend on multi-user.target.',
    ],
    hints:[
      'systemctl get-default && systemctl set-default multi-user.target',
      '[ -d /sys/firmware/efi ] && echo UEFI || echo BIOS; sed -i "s/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=3/" /etc/default/grub',
      '[ -d /sys/firmware/efi ] && grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg || grub2-mkconfig -o /boot/grub2/grub.cfg',
      'Edit /etc/default/grub: GRUB_CMDLINE_LINUX="... ipv6.disable=1" → regenerate',
      'echo "/dev/sdFAKE /fake xfs defaults 0 0" >> /etc/fstab && mount -a 2>&1; sed -i "/sdFAKE/d" /etc/fstab && mount -a',
      'Reboot → GRUB "e" → linux line: remove rhgb quiet, add rd.break → Ctrl+X → mount -o remount,rw /sysroot → chroot /sysroot → passwd root → touch /.autorelabel → exit → exit',
      'mkdir -p /etc/systemd/system/httpd.service.d && printf "[Service]\\nTimeoutStartSec=90\\n" > /etc/systemd/system/httpd.service.d/timeout.conf && systemctl daemon-reload',
      'systemctl isolate emergency.target',
      'cat /proc/cmdline',
      'systemctl list-dependencies multi-user.target --plain | head -15',
    ],
    solution:[
      {cmd:'systemctl get-default && systemctl set-default multi-user.target', desc:'Change default target'},
      {cmd:'[ -d /sys/firmware/efi ] && echo UEFI || echo BIOS', desc:'Detect boot type'},
      {cmd:'sed -i "s/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=3/" /etc/default/grub && grep GRUB_TIMEOUT /etc/default/grub', desc:'Set GRUB timeout'},
      {cmd:'grub2-mkconfig -o /boot/grub2/grub.cfg 2>/dev/null || grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg', desc:'Regenerate GRUB'},
      {cmd:"sed -i 's/GRUB_CMDLINE_LINUX=\"\\(.*\\)\"/GRUB_CMDLINE_LINUX=\"\\1 ipv6.disable=1\"/' /etc/default/grub && grep CMDLINE /etc/default/grub", desc:'Add kernel param'},
      {cmd:'echo "/dev/sdFAKE /fake xfs defaults 0 0" >> /etc/fstab && mount -a 2>&1 | head -5', desc:'Simulate bad fstab'},
      {cmd:"sed -i '/sdFAKE/d' /etc/fstab && mount -a && echo 'fstab OK'", desc:'Fix bad fstab'},
      {cmd:'# ROOT RESET:\n# 1. Reboot → GRUB → press e\n# 2. Find linux line: remove rhgb quiet, add: rd.break\n# 3. Ctrl+X\n# 4. mount -o remount,rw /sysroot\n# 5. chroot /sysroot\n# 6. passwd root\n# 7. touch /.autorelabel\n# 8. exit && exit', desc:'Root password reset procedure'},
      {cmd:'mkdir -p /etc/systemd/system/httpd.service.d && printf "[Service]\\nTimeoutStartSec=90\\n" > /etc/systemd/system/httpd.service.d/timeout.conf && systemctl daemon-reload', desc:'Service override'},
      {cmd:'cat /proc/cmdline', desc:'Verify kernel params'},
    ],
    validation:['systemctl get-default','grep GRUB_TIMEOUT /etc/default/grub','mount -a && echo OK','cat /proc/cmdline'],
    examTip:'Root reset = ALWAYS on exam. Memorize 6 steps: rd.break → remount rw → chroot → passwd → touch /.autorelabel → exit×2. Missing autorelabel = SELinux denials after reboot.',
  },
];

// ── TP ZONE EXERCISES ────────────────────────────────────────
const TP_EXERCISES = [
  {
    id:'tp-ess-1', domain:'essentials', title:'grep, find & Text Processing',
    description:'Practice advanced grep, find, awk, sed and text processing tools that appear throughout the exam.',
    difficulty:'medium', time:20,
    exercises:[
      {
        num:1,
        text:'Find all files on the system with the SUID bit set (regular files only). Save output to /tmp/suid_files.txt. Count how many there are.',
        correction:'find / -type f -perm /4000 2>/dev/null | tee /tmp/suid_files.txt | wc -l',
      },
      {
        num:2,
        text:'Search /var/log recursively for lines containing "error" OR "fail" (case-insensitive). Show only the unique filenames that contain matches.',
        correction:'grep -riEl "error|fail" /var/log/ 2>/dev/null',
      },
      {
        num:3,
        text:'Using awk, print only the username (field 1) and shell (field 7) from /etc/passwd, separated by " uses shell: ". Only show users whose shell is NOT /sbin/nologin.',
        correction:"awk -F: '$7 != \"/sbin/nologin\" {print $1, \"uses shell:\", $7}' /etc/passwd",
      },
      {
        num:4,
        text:'Using sed, create /tmp/hosts_clean.txt from /etc/hosts with all comment lines (starting with #) and empty lines removed.',
        correction:"sed '/^#/d;/^$/d' /etc/hosts > /tmp/hosts_clean.txt && cat /tmp/hosts_clean.txt",
      },
      {
        num:5,
        text:'Find the 5 largest files in /usr/bin. Display their size and name, sorted from largest to smallest.',
        correction:'find /usr/bin -type f -exec du -sh {} + 2>/dev/null | sort -rh | head -5',
      },
    ],
  },
  {
    id:'tp-usr-1', domain:'users', title:'sudo Configuration',
    description:'Configure granular sudo privileges — a critical exam scenario.',
    difficulty:'medium', time:20,
    exercises:[
      {
        num:1,
        text:'Add alice to the wheel group to give her full sudo access.',
        correction:'usermod -aG wheel alice',
      },
      {
        num:2,
        text:'Create /etc/sudoers.d/devteam (mode 440). In it: bob can run systemctl restart httpd and systemctl restart nginx as root without a password.',
        correction:'echo "bob ALL=(root) NOPASSWD: /usr/bin/systemctl restart httpd, /usr/bin/systemctl restart nginx" > /etc/sudoers.d/devteam && chmod 440 /etc/sudoers.d/devteam && visudo -c',
      },
      {
        num:3,
        text:'All members of the "devops" group can run any command as any user without a password. Add this to /etc/sudoers.d/devteam.',
        correction:'echo "%devops ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/devteam && chmod 440 /etc/sudoers.d/devteam && visudo -c',
      },
      {
        num:4,
        text:'Test bob\'s sudo: switch to bob and run "sudo systemctl status httpd". Show alice\'s effective sudo rules.',
        correction:'su - bob -c "sudo systemctl status httpd" && sudo -l -U alice',
      },
      {
        num:5,
        text:'Restrict alice: she can run sudo only between 09:00 and 18:00 on weekdays. Use the time restriction syntax in sudoers.',
        correction:'# In /etc/sudoers.d/alice-time:\n# alice ALL=(ALL) PASSWD: ALL\n# Cmnd_Alias ANYTIME = ...\n# Time restriction with sudoers runas_default requires sudoers 1.9+\n# Basic: alice ALL=(ALL) PASSWD: ALL   (then enforce time in script)',
      },
    ],
  },
  {
    id:'tp-perm-1', domain:'permissions', title:'ACL Complex Scenario',
    description:'Configure fine-grained ACL with defaults, mask, and inheritance.',
    difficulty:'hard', time:25,
    exercises:[
      {
        num:1,
        text:'Create /data/project. Configure: alice=rwx, bob=r-x, carol (create if needed)=---, qa group=rw-, all via ACL.',
        correction:'mkdir -p /data/project\nsetfacl -m u:alice:rwx,u:bob:r-x,u:carol:---,g:qa:rw- /data/project 2>/dev/null || (useradd carol 2>/dev/null; setfacl -m u:alice:rwx,u:bob:r-x,u:carol:---,g:qa:rw- /data/project)',
      },
      {
        num:2,
        text:'Set default ACLs so new files inherit: alice=rwx, bob=r-x, qa=rw-. Test by creating a file as alice inside /data/project.',
        correction:'setfacl -d -m u:alice:rwx,u:bob:r-x,g:qa:rw- /data/project\nsu - alice -c "touch /data/project/test_$(date +%s).txt" 2>/dev/null\ngetfacl /data/project',
      },
      {
        num:3,
        text:'Show the ACL mask of /data/project. Explain what it limits. Then change the mask to r-- and observe the effective permissions for alice.',
        correction:'getfacl /data/project | grep mask\n# mask limits NAMED users and groups (not owner, not other)\nsetfacl -m m::r-- /data/project && getfacl /data/project\n# alice has rwx but mask is r-- → effective = r--',
      },
      {
        num:4,
        text:'Backup the ACL of /data/project to /tmp/project_acl.bak. Remove all ACLs. Then restore from backup.',
        correction:'getfacl /data/project > /tmp/project_acl.bak\nsetfacl -b /data/project\ngetfacl /data/project  # shows standard perms only\nsetfacl --restore=/tmp/project_acl.bak\ngetfacl /data/project  # ACL restored',
      },
    ],
  },
  {
    id:'tp-str-1', domain:'storage', title:'autofs & NFS Configuration',
    description:'Configure autofs to auto-mount NFS shares — very common exam scenario.',
    difficulty:'hard', time:25,
    exercises:[
      {
        num:1,
        text:'Install autofs. Configure the master map at /etc/auto.master to handle /mnt/remote with map file /etc/auto.remote and 60s timeout.',
        correction:'dnf install -y autofs\necho "/mnt/remote  /etc/auto.remote  --timeout=60" >> /etc/auto.master',
      },
      {
        num:2,
        text:'Create /etc/auto.remote: map key "data" to nfsserver:/exports/data with rw,sync options; map key "backup" to nfsserver:/exports/backup with ro.',
        correction:'cat > /etc/auto.remote << EOF\ndata    -rw,sync    nfsserver:/exports/data\nbackup  -ro         nfsserver:/exports/backup\nEOF',
      },
      {
        num:3,
        text:'Enable and start autofs. Show how to test that auto-mount works (access /mnt/remote/data) and verify with mount.',
        correction:'systemctl enable --now autofs\nls /mnt/remote/data 2>/dev/null || echo "(NFS server not available - that is OK in lab)"\nmount | grep autofs',
      },
      {
        num:4,
        text:'Configure autofs for user home directories: any user home from nfsserver:/home/USERNAME should auto-mount at /home/USERNAME.',
        correction:'# /etc/auto.master:\necho "/home  /etc/auto.home" >> /etc/auto.master\n# /etc/auto.home:\necho "*  -rw,sync  nfsserver:/home/&" > /etc/auto.home\n# & is replaced by wildcard match (*), so alice → nfsserver:/home/alice\nsystemctl restart autofs',
      },
    ],
  },
  {
    id:'tp-proc-1', domain:'processes', title:'Advanced Process & Signal Management',
    description:'Process control, signals, and systemd timer creation.',
    difficulty:'medium', time:20,
    exercises:[
      {
        num:1,
        text:'Start a sleep 9999 process. Get its PID. Change its nice value to 10 using renice. Verify the change with ps.',
        correction:'sleep 9999 &\nPID=$!\nrenice -n 10 -p $PID\nps -o pid,nice,comm -p $PID',
      },
      {
        num:2,
        text:'Write /usr/local/bin/safe_kill.sh: takes a process name, sends SIGTERM, waits 5 seconds, sends SIGKILL if still running. Make it executable.',
        correction:"cat > /usr/local/bin/safe_kill.sh << 'EOF'\n#!/bin/bash\n[ -z \"$1\" ] && echo \"Usage: $0 procname\" && exit 1\nPID=$(pgrep -x \"$1\" | head -1)\n[ -z \"$PID\" ] && echo \"Not running: $1\" && exit 0\necho \"Sending SIGTERM to $1 (PID $PID)\"\nkill -15 $PID\nsleep 5\nif kill -0 $PID 2>/dev/null; then\n  echo \"Still running — sending SIGKILL\"\n  kill -9 $PID\nelse\n  echo \"$1 stopped cleanly\"\nfi\nEOF\nchmod +x /usr/local/bin/safe_kill.sh",
      },
      {
        num:3,
        text:'Create a systemd timer (daily at 4:00 AM) to run /usr/local/bin/cleanup.sh. Make it persistent so missed runs are executed after boot.',
        correction:"cat > /etc/systemd/system/daily-cleanup.service << 'EOF'\n[Unit]\nDescription=Daily Cleanup\n[Service]\nType=oneshot\nExecStart=/usr/local/bin/cleanup.sh\nEOF\ncat > /etc/systemd/system/daily-cleanup.timer << 'EOF'\n[Unit]\nDescription=Run daily cleanup at 4AM\n[Timer]\nOnCalendar=*-*-* 04:00:00\nPersistent=true\n[Install]\nWantedBy=timers.target\nEOF\nsystemctl daemon-reload && systemctl enable --now daily-cleanup.timer",
      },
      {
        num:4,
        text:'Find all zombie processes on the system. Explain what they are and how to handle them.',
        correction:'ps aux | awk \'$8=="Z" {print "ZOMBIE PID:",$2, "CMD:",$11}\'\n# Zombies = dead processes whose parent has not called wait()\n# You cannot kill zombies (already dead)\n# Solution: kill the PARENT process (it will reap the zombie)\n# OR wait for init to reap it\n# parent PID: ps -o ppid= -p ZOMBIE_PID',
      },
    ],
  },
  {
    id:'tp-net-1', domain:'networking', title:'Advanced Network Configuration',
    description:'Static routes, secondary connections, network troubleshooting.',
    difficulty:'medium', time:20,
    exercises:[
      {
        num:1,
        text:'Add a static route: traffic to 172.16.0.0/16 should go via gateway 192.168.100.254. Make it persistent using nmcli.',
        correction:'CON=$(nmcli -t -f NAME connection show --active | head -1)\nnmcli connection modify "$CON" +ipv4.routes "172.16.0.0/16 192.168.100.254"\nnmcli connection up "$CON"\nip route show | grep 172.16',
      },
      {
        num:2,
        text:'Use ss to find what process is listening on port 22. Then check if port 80 is open on localhost.',
        correction:'ss -tlnp | grep :22\nss -tlnp | grep :80\n# Or: echo >/dev/tcp/localhost/80 && echo "Port 80 open" 2>/dev/null || echo "Port 80 closed"',
      },
      {
        num:3,
        text:'Show detailed interface statistics (bytes sent/received) for all interfaces. Show the routing table in both short and detailed format.',
        correction:'ip -s link show\nip route show\nip route show table all | head -20',
      },
      {
        num:4,
        text:'Configure /etc/nsswitch.conf so DNS is checked BEFORE /etc/hosts for hostname lookups. Test that it works. Then revert it.',
        correction:'# View current:\ngrep ^hosts /etc/nsswitch.conf\n# Change: "hosts: files dns" → "hosts: dns files"\ncp /etc/nsswitch.conf /etc/nsswitch.conf.bak\nsed -i "s/^hosts:.*/hosts: dns files myhostname/" /etc/nsswitch.conf\ngetent hosts localhost\n# Revert:\ncp /etc/nsswitch.conf.bak /etc/nsswitch.conf',
      },
    ],
  },
  {
    id:'tp-svc-1', domain:'services', title:'journalctl & Service Debugging',
    description:'Deep dive into journalctl, service debugging, and systemd unit overrides.',
    difficulty:'medium', time:20,
    exercises:[
      {
        num:1,
        text:'Show all logs from the PREVIOUS boot. Show only CRITICAL and higher priority logs system-wide. Show sshd logs from the last 2 hours.',
        correction:'journalctl -b -1\njournalctl -p crit --no-pager\njournalctl -u sshd --since "2 hours ago" --no-pager',
      },
      {
        num:2,
        text:'Show how much disk space the journal uses. Keep only the last 100MB. Make the journal persistent across reboots.',
        correction:'journalctl --disk-usage\njournalctl --vacuum-size=100M\nmkdir -p /var/log/journal\ngrep -q "^Storage" /etc/systemd/journald.conf && sed -i "s/^Storage.*/Storage=persistent/" /etc/systemd/journald.conf || echo "Storage=persistent" >> /etc/systemd/journald.conf\nsystemctl restart systemd-journald',
      },
      {
        num:3,
        text:'Create a systemd service override for httpd that: sets TimeoutStartSec=120, adds restart on failure (Restart=on-failure), and sets RestartSec=5.',
        correction:'mkdir -p /etc/systemd/system/httpd.service.d\ncat > /etc/systemd/system/httpd.service.d/custom.conf << EOF\n[Service]\nTimeoutStartSec=120\nRestart=on-failure\nRestartSec=5\nEOF\nsystemctl daemon-reload\nsystemctl show httpd | grep -E "Timeout|Restart"',
      },
      {
        num:4,
        text:'httpd fails to start. Diagnose it: use systemctl status, journalctl, and httpd -t. List the typical causes and fixes.',
        correction:'systemctl status httpd\njournalctl -u httpd -n 30 --no-pager\nhttpd -t  # syntax check\n# Common causes:\n# 1. Port already in use: ss -tlnp | grep :80\n# 2. SELinux context wrong: ls -Zd /var/www/html, restorecon\n# 3. SELinux port: semanage port -l | grep http\n# 4. Config syntax error: httpd -t\n# 5. Permission denied on files: ls -la DocumentRoot',
      },
    ],
  },
  {
    id:'tp-sec-1', domain:'security', title:'SELinux Policy & Firewall Zones',
    description:'Advanced SELinux management and firewalld zone configuration.',
    difficulty:'hard', time:30,
    exercises:[
      {
        num:1,
        text:'Find all SELinux booleans related to httpd. Enable httpd_use_nfs permanently. Verify it is on after re-querying.',
        correction:'getsebool -a | grep httpd\nsetsebool -P httpd_use_nfs on\ngetsebool httpd_use_nfs',
      },
      {
        num:2,
        text:'Configure firewalld: public zone has http+https. Remove ssh from public. Add source 192.168.100.0/24 to trusted zone. Add ssh to trusted only. Reload and verify both zones.',
        correction:'firewall-cmd --permanent --zone=public --add-service=http --add-service=https\nfirewall-cmd --permanent --zone=public --remove-service=ssh\nfirewall-cmd --permanent --zone=trusted --add-source=192.168.100.0/24\nfirewall-cmd --permanent --zone=trusted --add-service=ssh\nfirewall-cmd --reload\nfirewall-cmd --zone=public --list-all\nfirewall-cmd --zone=trusted --list-all',
      },
      {
        num:3,
        text:'Add a rich rule to the public zone: log and DROP all TCP traffic to port 23 (telnet). Test with firewall-cmd --list-rich-rules.',
        correction:"firewall-cmd --permanent --zone=public --add-rich-rule='rule family=ipv4 port port=23 protocol=tcp log prefix=\"TELNET-DROP: \" drop'\nfirewall-cmd --reload\nfirewall-cmd --zone=public --list-rich-rules",
      },
      {
        num:4,
        text:'Change the DocumentRoot of httpd to /srv/webdata. Fix any SELinux issues. Verify curl http://localhost works.',
        correction:'mkdir -p /srv/webdata && echo "SELinux Lab" > /srv/webdata/index.html\nsed -i "s|DocumentRoot .*|DocumentRoot \"/srv/webdata\"|" /etc/httpd/conf/httpd.conf\nsemanage fcontext -a -t httpd_sys_content_t "/srv/webdata(/.*)?"\nrestorecon -Rv /srv/webdata\nsystemctl restart httpd\ncurl http://localhost',
      },
      {
        num:5,
        text:'An application tries to use port 9443/tcp but SELinux blocks it. Allow it for the https_port_t type. Verify.',
        correction:'semanage port -a -t https_port_t -p tcp 9443\nsemanage port -l | grep 9443',
      },
    ],
  },
  {
    id:'tp-scr-1', domain:'scripting', title:'Advanced Bash Scripts',
    description:'Write production-quality bash scripts for common sysadmin tasks.',
    difficulty:'hard', time:35,
    exercises:[
      {
        num:1,
        text:'Write a script that accepts a directory as argument. Prints: total files, total dirs, total size, top 3 largest files, number of .log files.',
        correction:"cat > /usr/local/bin/dir_report.sh << 'EOF'\n#!/bin/bash\nDIR=\"${1:-.}\"\n[ ! -d \"$DIR\" ] && echo \"ERROR: Not a directory: $DIR\" && exit 1\necho \"=== Report for: $DIR ===\"\necho \"Files: $(find \"$DIR\" -type f | wc -l)\"\necho \"Dirs:  $(find \"$DIR\" -type d | wc -l)\"\necho \"Size:  $(du -sh \"$DIR\" | cut -f1)\"\necho \"Log files: $(find \"$DIR\" -name '*.log' | wc -l)\"\necho \"Top 3 largest:\"\nfind \"$DIR\" -type f -exec du -sh {} + 2>/dev/null | sort -rh | head -3\nEOF\nchmod +x /usr/local/bin/dir_report.sh\nbash /usr/local/bin/dir_report.sh /var/log",
      },
      {
        num:2,
        text:'Write a script that monitors /var/log/secure for failed SSH attempts. Prints IPs that failed more than 5 times, sorted by count (desc).',
        correction:"cat > /usr/local/bin/ssh_fails.sh << 'EOF'\n#!/bin/bash\nLOGFILE=/var/log/secure\n[ ! -f \"$LOGFILE\" ] && LOGFILE=/var/log/auth.log\n[ ! -f \"$LOGFILE\" ] && echo \"Log file not found\" && exit 1\necho \"=== IPs with >5 failed SSH attempts ===\"\ngrep 'Failed password' \"$LOGFILE\" 2>/dev/null | \\\n  awk '{for(i=1;i<=NF;i++) if($i==\"from\") print $(i+1)}' | \\\n  sort | uniq -c | sort -rn | awk '$1>5 {print $2, \"failed:\", $1, \"times\"}'\nEOF\nchmod +x /usr/local/bin/ssh_fails.sh",
      },
      {
        num:3,
        text:'Write a comprehensive system health check script (with set -euo pipefail and trap for errors). Checks: disk >80%, memory <20% free, failed services, sshd running. Output to /var/log/health.log.',
        correction:"cat > /usr/local/bin/health_check.sh << 'EOF'\n#!/bin/bash\nset -uo pipefail\nLOG=/var/log/health.log\ntrap 'echo \"$(date): ERROR at line $LINENO\" >> \"$LOG\"' ERR\nlog() { echo \"$(date '+%Y-%m-%d %H:%M:%S'): $*\" | tee -a \"$LOG\"; }\nlog \"=== Health Check START ===\"\nDISK=$(df / | awk 'NR==2{gsub(/%/,\"\",$5); print $5}')\n[ \"$DISK\" -ge 80 ] && log \"WARN: / is ${DISK}% full\"\nFREE=$(free | awk '/^Mem/{printf \"%d\", ($4/$2)*100}')\n[ \"$FREE\" -lt 20 ] && log \"WARN: Only ${FREE}% memory free\"\nFAILED=$(systemctl list-units --failed --no-pager --no-legend 2>/dev/null | wc -l)\n[ \"$FAILED\" -gt 0 ] && log \"WARN: $FAILED failed unit(s)\"\nsystemctl is-active sshd &>/dev/null || { log \"WARN: sshd not running — restarting\"; systemctl start sshd; }\nlog \"=== Health Check END ===\"\nEOF\nchmod +x /usr/local/bin/health_check.sh",
      },
      {
        num:4,
        text:'Write a script that accepts start|stop|status|restart as argument and manages a custom application (simulate with sleep). The script should use a PID file at /var/run/myapp.pid.',
        correction:"cat > /usr/local/bin/myapp_ctl.sh << 'EOF'\n#!/bin/bash\nPIDFILE=/var/run/myapp.pid\ncase \"$1\" in\n  start)\n    [ -f \"$PIDFILE\" ] && kill -0 $(cat \"$PIDFILE\") 2>/dev/null && echo \"Already running\" && exit 0\n    sleep 99999 &\n    echo $! > \"$PIDFILE\"\n    echo \"Started (PID $(cat $PIDFILE))\"\n    ;;\n  stop)\n    [ ! -f \"$PIDFILE\" ] && echo \"Not running\" && exit 0\n    kill $(cat \"$PIDFILE\") 2>/dev/null && rm -f \"$PIDFILE\" && echo \"Stopped\"\n    ;;\n  status)\n    [ -f \"$PIDFILE\" ] && kill -0 $(cat \"$PIDFILE\") 2>/dev/null && echo \"Running (PID $(cat $PIDFILE))\" || echo \"Not running\"\n    ;;\n  restart) $0 stop; sleep 1; $0 start ;;\n  *) echo \"Usage: $0 {start|stop|status|restart}\"; exit 1 ;;\nesac\nEOF\nchmod +x /usr/local/bin/myapp_ctl.sh",
      },
    ],
  },
  {
    id:'tp-con-1', domain:'containers', title:'Podman Advanced Usage',
    description:'Container management, volumes, pods, and systemd integration.',
    difficulty:'medium', time:25,
    exercises:[
      {
        num:1,
        text:'Run a mariadb container as root: name=mydb, port 3306→3306, env MARIADB_ROOT_PASSWORD=Secret1!, volume /var/lib/mydb:/var/lib/mysql:Z, detached. Verify it is running.',
        correction:'mkdir -p /var/lib/mydb\npodman run -d --name mydb -p 3306:3306 -e MARIADB_ROOT_PASSWORD=Secret1! -v /var/lib/mydb:/var/lib/mysql:Z docker.io/library/mariadb\npodman ps | grep mydb',
      },
      {
        num:2,
        text:'Connect to the mydb container and run a SQL command: SHOW DATABASES; then CREATE DATABASE rhcsa_test;',
        correction:'podman exec -it mydb mariadb -uroot -pSecret1! -e "SHOW DATABASES; CREATE DATABASE IF NOT EXISTS rhcsa_test;"',
      },
      {
        num:3,
        text:'Export the nginx image to /tmp/nginx_backup.tar. Remove the local image. Re-import it and tag it as "myregistry.local/nginx:v1".',
        correction:'podman pull docker.io/library/nginx 2>/dev/null || true\npodman save -o /tmp/nginx_backup.tar nginx\npodman rmi nginx 2>/dev/null || true\npodman load -i /tmp/nginx_backup.tar\npodman tag nginx myregistry.local/nginx:v1\npodman images | grep nginx',
      },
      {
        num:4,
        text:'Create a pod named "webapp" with port 8888→80. Add an nginx container to the pod. Verify both the pod and container are running.',
        correction:'podman pod create --name webapp -p 8888:80\npodman run -d --pod webapp --name web-nginx nginx\npodman pod ps\npodman ps --pod',
      },
    ],
  },
  {
    id:'tp-boot-1', domain:'boot', title:'Complete Recovery Scenarios',
    description:'Simulate and recover from common boot and system failure scenarios.',
    difficulty:'hard', time:30,
    exercises:[
      {
        num:1,
        text:'SCENARIO: System boots to emergency mode due to bad fstab. Describe every step to fix it from the emergency shell.',
        correction:'# At emergency shell:\n# 1. Login as root with password\n# 2. Remount root rw:\nmount -o remount,rw /\n# 3. Edit fstab:\nvim /etc/fstab   # comment out or fix the bad line\n# 4. Test:\nmount -a\n# 5. If OK, reboot:\nsystemctl reboot\n# OR if still issues:\nsystemctl default  # try to reach default target',
      },
      {
        num:2,
        text:'httpd fails to start after a system update. Write the COMPLETE diagnosis procedure using 5 different diagnostic commands.',
        correction:'# 1. Check service status:\nsystemctl status httpd\n# 2. Read journal for errors:\njournalctl -u httpd -n 30 --no-pager\n# 3. Test config syntax:\nhttpd -t\n# 4. Check port conflict:\nss -tlnp | grep :80\n# 5. Check SELinux:\naudit search -m avc -ts recent 2>/dev/null | grep httpd | tail -5\nls -Zd /var/www/html\n# 6. Check firewall:\nfirewall-cmd --list-all',
      },
      {
        num:3,
        text:'You need to boot into rescue mode WITHOUT rebooting. Do it. Show how to return to normal mode afterward.',
        correction:'systemctl isolate rescue.target\n# Enter root password when prompted\n# You are now in rescue mode (single user)\n# To return to normal:\nsystemctl default\n# OR:\nsystemctl isolate multi-user.target',
      },
      {
        num:4,
        text:'Write a GRUB2 recovery checklist: list every file you might need to edit and every command to run to fix common GRUB issues.',
        correction:'# GRUB2 Recovery Checklist:\n# FILES TO EDIT:\n# /etc/default/grub          - timeout, cmdline, etc.\n# /etc/grub.d/40_custom      - custom menu entries\n\n# COMMANDS:\n# Detect boot type:\n[ -d /sys/firmware/efi ] && echo UEFI || echo BIOS\n\n# Regenerate config:\ngrub2-mkconfig -o /boot/grub2/grub.cfg          # BIOS\ngrub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg  # UEFI\n\n# Reinstall GRUB (if MBR corrupted):\ngrub2-install /dev/sda   # BIOS only\n\n# List installed kernels:\nrpm -qa kernel | sort\ngrubby --info=ALL\n\n# Set default kernel:\ngrubby --set-default /boot/vmlinuz-VERSION',
      },
    ],
  },
];
